cnpm install --save echarts@4.9.0
cnpm install --save sortablejs@1.13.0
cnpm install --save vue-image-crop-upload@2.5.0
cnpm install --save vue-quill-editor@3.0.6
cnpm install --save vue-slicksort@1.2.0
cnpm install --save vue-cropper@0.5.6
cnpm install --save moment@2.29.1
cnpm install --save quill-image-resize-module@3.0.0
cnpm install --save print-js@1.0.63
