cnpm intall
cnpm install --save @riophae/vue-treeselect@0.3.0
cnpm install vue-jsonp@0.1.8 --save
cnpm install --save vue-cropper@0.5.6
cnpm install js-base64@3.7.2 --save
cnpm install --save print-js@1.0.63
cnpm install --save ant-design-vue@1.3.13
cnpm install --save echarts@4.9.0
cnpm install --save vue-pdf@4.2.0
cnpm install --save cornerstone-core@2.3.0
cnpm install --save cornerstone-tools@5.3.0
cnpm install --save cornerstone-wado-image-loader@3.3.2
cnpm install --save cornerstone-web-image-loader@2.1.1
cnpm install --save hammerjs@2.0.8
cnpm install --save jquery@3.6.0
cnpm install --save jsdom@16.4.0
cnpm install --save xmlhttprequest@1.8.0
cnpm install --save navigator@1.0.1
cnpm install --save location@0.0.1
cnpm install --save @form-create/element-ui@1.0.20
cnpm install --save @riophae/vue-treeselect@0.0.38
cnpm install --save sortablejs@1.13.0
cnpm install  --save vue-image-crop-upload@2.5.0
cnpm install --save echarts
 
cnpm install --save vue-slicksort
cnpm install --save v-charts
cnpm install --save vue-image-crop-upload@2.5.0
cnpm install --save vue-quill-editor@3.0.6
cnpm install --save vue-slicksort@1.2.0
cnpm install --save moment@2.29.1
cnpm install --save quill-image-resize-module@3.0.0
cnpm install  --save mescroll.js@1.4.2
cnpm install  --save qrcodejs2@0.0.2
cnpm install  --save vue-video-player@5.0.2
cnpm install  --save animate.css@4.1.1
cnpm install  --save sortablejs@1.13.0
cnpm install  --save video.js@7.11.8
cnpm install  --save vue-quill-editor@3.0.6  
cnpm install  --save v-viewer@1.5.1 
cnpm run build
