cnpm install --save print-js@1.0.63
cnpm install --save ant-design-vue@1.3.13
cnpm install --save echarts@4.9.0
cnpm install --save vue-pdf@4.2.0
cnpm install --save cornerstone-core@2.3.0
cnpm install --save cornerstone-tools@5.3.0
cnpm install --save cornerstone-wado-image-loader@3.3.2
cnpm install --save cornerstone-web-image-loader@2.1.1
cnpm install --save hammerjs@2.0.8
