cnpm install  --save mescroll.js@1.4.2
cnpm install  --save vue-image-crop-upload@2.5.0
cnpm install  --save qrcodejs2@0.0.2
cnpm install  --save vue-video-player@5.0.2
cnpm install  --save animate.css@4.1.1
cnpm install  --save sortablejs@1.13.0
cnpm install  --save video.js@7.11.8
cnpm install  --save vue-quill-editor@3.0.6  
cnpm install  --save v-viewer@1.5.1 
cnpm install --save @riophae/vue-treeselect@0.0.38
