// 输血观察单
export const BloodTransfusion = [{
  'columns': [{
    'padding': '24px 18px 24px 19px',
    'gapLR': '0',
    'children': [{
      'columns': [{
        'padding': '0',
        'gapLR': '0',
        'children': [{
          'score': 0,
          'type': 'date',
          'value': '',
          'config': {
            'uniId': 'guanchadan_shuxueguanchadan_riqi',
            'clearable': false,
            'prefixColor': '#666666',
            'readonly': false,
            'prefix': '日期：',
            'prefixPaddingRight': '0',
            'prefixAlign': 'right',
            'width': '182px',
            'disabled': false,
            'placeholder': '',
            'type': 'date',
            'prefixWidth': '140px'
          },
          'key': '1611220411000_75740',
          'his_id': 'date'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '',
        'childWidth': 'auto',
        'align': 'flex-start',
        'gapTB': '0',
        'direction': 'column'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#EEF0F6',
        'borderWidth': '0px',
        'borderStyle': 'solid'
      },
      'key': '1611220411000_84979'
    }, {
      'columns': [{
        'padding': '0',
        'gapLR': '0',
        'children': [{
          'type': 'text',
          'value': '',
          'config': {
            'color': '#000',
            'weight': '',
            'fontSize': '16px',
            'label': '输血前评估',
            'align': 'left'
          },
          'key': '1611220411000_53726'
        }, {
          'columns': [{
            'padding': '7px 0',
            'gapLR': '0',
            'children': [{
              'score': 0,
              'type': 'date',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_celiangshijian',
                'clearable': false,
                'prefixColor': '#666666',
                'readonly': false,
                'prefix': '测量时间：',
                'prefixPaddingRight': '0',
                'prefixAlign': 'right',
                'width': '182px',
                'disabled': false,
                'placeholder': '请选择',
                'type': 'time',
                'prefixWidth': '140px',
                'showFormat': 'HH:mm'
              },
              'key': '1611220411000_86167',
              'his_id': 'time1'
            }, {
              'score': 0,
              'options': [{
                'score': 0,
                'id': '1611220411000_32638-0',
                'label': '拒测'
              }, {
                'score': 0,
                'id': '1611220411000_32638-1',
                'label': '外出'
              }, {
                'score': 0,
                'id': '1611220411000_32638-2',
                'label': '请假'
              }, {
                'score': 0,
                'id': '1611220411000_32638-3',
                'label': '不升'
              }],
              'type': 'select',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_tiwen',
                'filterable': true,
                'prefixColor': '#666666',
                'prefix': '体温：',
                'prefixAlign': 'right',
                'suffix': '℃',
                'suffixWidth': '50px',
                'suffixPaddingLeft': '12px',
                'suffixColor': '#333333',
                'prefixPaddingRight': '0',
                'suffixAlign': 'left',
                'width': '182px',
                'placeholder': '请输入',
                'prefixWidth': '140px',
                'allowCreate': true
              },
              'key': '1611220411000_32638',
              'his_id': 'tiwen1'
            }, {
              'score': 0,
              'mConfig': {},
              'type': 'input',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_maibo',
                'hasPadding': true,
                'prefixColor': '#666666',
                'prefix': '脉搏：',
                'prefixAlign': 'right',
                'suffix': '次/分',
                'suffixWidth': '50px',
                'suffixPaddingLeft': '12px',
                'suffixColor': '#333333',
                'prefixPaddingRight': '0',
                'suffixAlign': 'left',
                'width': '182px',
                'placeholder': '请输入',
                'maxlength': 10,
                'prefixWidth': '140px'
              },
              'key': '1611220411000_55059',
              'his_id': 'maibo1'
            }, {
              'score': 0,
              'mConfig': {},
              'type': 'input',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_huxi',
                'hasPadding': true,
                'prefixColor': '#666666',
                'prefix': '呼吸：',
                'prefixAlign': 'right',
                'suffix': '次/分',
                'suffixWidth': '50px',
                'suffixPaddingLeft': '12px',
                'suffixColor': '#333333',
                'prefixPaddingRight': '0',
                'suffixAlign': 'left',
                'width': '182px',
                'placeholder': '请输入',
                'maxlength': 10,
                'prefixWidth': '140px'
              },
              'key': '1611298934000_43674',
              'his_id': 'huxi1'
            }, {
              'score': 0,
              'mConfig': {},
              'type': 'input',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_shousuoya',
                'hasPadding': true,
                'prefixColor': '#666666',
                'prefix': '收缩压：',
                'prefixAlign': 'right',
                'suffix': 'mmol/L',
                'suffixWidth': '50px',
                'suffixPaddingLeft': '12px',
                'suffixColor': '#333333',
                'prefixPaddingRight': '0',
                'suffixAlign': 'left',
                'width': '182px',
                'placeholder': '请输入',
                'maxlength': 10,
                'prefixWidth': '140px'
              },
              'key': '1611298901000_36632',
              'his_id': 'shousuoya1'
            }, {
              'score': 0,
              'mConfig': {},
              'type': 'input',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_shuzhangya',
                'hasPadding': true,
                'prefixColor': '#666666',
                'prefix': '舒张压：',
                'prefixAlign': 'right',
                'suffix': 'mmol/L',
                'suffixWidth': '50px',
                'suffixPaddingLeft': '12px',
                'suffixColor': '#333333',
                'prefixPaddingRight': '0',
                'suffixAlign': 'left',
                'width': '182px',
                'placeholder': '请输入',
                'maxlength': 10,
                'prefixWidth': '140px'
              },
              'key': '1611298948000_22573',
              'his_id': 'shuzhangya1'
            }, {
              'score': 0,
              'options': [{
                'score': 0,
                'id': '1611220411000_85216-0',
                'label': '是'
              }, {
                'score': 0,
                'id': '1611220411000_85216-1',
                'label': '否'
              }],
              'type': 'select',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_yicixinggangzhen',
                'filterable': true,
                'prefixColor': '#666666',
                'prefix': '一次性钢针：',
                'prefixAlign': 'right',
                'prefixPaddingRight': '0',
                'width': '182px',
                'placeholder': '请输入',
                'prefixWidth': '140px',
                'allowCreate': true
              },
              'key': '1611220411000_85216',
              'his_id': 'gangzhen'
            }, {
              'score': 0,
              'mConfig': {},
              'options': [{
                'score': 0,
                'id': '1611220411000_53003-0',
                'label': '是'
              }, {
                'score': 0,
                'id': '1611220411000_53003-1',
                'label': '否'
              }],
              'type': 'select',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_waizhoujingmaizhen',
                'filterable': true,
                'prefixColor': '#666666',
                'prefix': '外周静脉置针：',
                'prefixPaddingRight': '0',
                'prefixAlign': 'right',
                'width': '182px',
                'placeholder': '请输入',
                'prefixWidth': '140px',
                'allowCreate': true
              },
              'key': '1611220411000_53003',
              'his_id': 'zhiliuzhen'
            }, {
              'score': 0,
              'mConfig': {},
              'type': 'select',
              'value': '',
              'options': [{
                'score': 0,
                'id': '1611220411000_49290-0',
                'label': '是'
              }, {
                'score': 0,
                'id': '1611220411000_49290-1',
                'label': '否'
              }],
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_zhongxinjingmaidaoguan',
                'filterable': true,
                'prefixColor': '#666666',
                'prefix': '中心静脉导管：',
                'prefixPaddingRight': '0',
                'prefixAlign': 'right',
                'width': '182px',
                'placeholder': '请输入',
                'prefixWidth': '140px',
                'allowCreate': true
              },
              'key': '1611220411000_49290',
              'his_id': 'daoguan'
            }, {
              'score': 0,
              'mConfig': {},
              'type': 'input',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_qitatujing',
                'hasPadding': true,
                'prefixColor': '#666666',
                'prefix': '其他途径：',
                'prefixPaddingRight': '0',
                'prefixAlign': 'right',
                'width': '182px',
                'placeholder': '请输入',
                'maxlength': 10,
                'prefixWidth': '140px'
              },
              'key': '1611220411000_88808',
              'his_id': 'qitatujing'
            }, {
              'score': 0,
              'mConfig': {},
              'type': 'input',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_hongxibao',
                'hasPadding': true,
                'prefixColor': '#666666',
                'prefix': '红细胞（U）：',
                'prefixPaddingRight': '0',
                'prefixAlign': 'right',
                'width': '182px',
                'placeholder': '请输入',
                'maxlength': 10,
                'prefixWidth': '140px'
              },
              'key': '1611220411000_73558',
              'his_id': 'hongxibao'
            }, {
              'score': 0,
              'mConfig': {},
              'type': 'input',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_xuexiaobanzhiliaoliang',
                'hasPadding': true,
                'prefixColor': '#666666',
                'prefix': '血小板（治疗量）：',
                'prefixPaddingRight': '0',
                'prefixAlign': 'right',
                'width': '182px',
                'placeholder': '请输入',
                'maxlength': 10,
                'prefixWidth': '140px'
              },
              'key': '1611220411000_68421',
              'his_id': 'xuexiaoban'
            }, {
              'score': 0,
              'mConfig': {},
              'type': 'input',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_xuejiang',
                'hasPadding': true,
                'prefixColor': '#666666',
                'prefix': '血浆：',
                'prefixAlign': 'right',
                'suffix': 'ml',
                'suffixWidth': '50px',
                'suffixPaddingLeft': '12px',
                'suffixColor': '#333333',
                'prefixPaddingRight': '0',
                'suffixAlign': 'left',
                'width': '182px',
                'placeholder': '请输入',
                'maxlength': 10,
                'prefixWidth': '140px'
              },
              'key': '1611220411000_86237',
              'his_id': 'xuejiang'
            }, {
              'score': 0,
              'mConfig': {},
              'type': 'input',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_qitazhonglei',
                'hasPadding': true,
                'prefixColor': '#666666',
                'prefix': '其他种类：',
                'prefixPaddingRight': '0',
                'prefixAlign': 'right',
                'width': '182px',
                'placeholder': '请输入',
                'maxlength': 10,
                'prefixWidth': '140px'
              },
              'key': '1611220411000_46588',
              'his_id': 'qitazhonglei'
            }, {
              'score': 0,
              'mConfig': {},
              'type': 'input',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_zhixingzhe',
                'hasPadding': true,
                'prefixColor': '#666666',
                'prefix': '执行者：',
                'prefixPaddingRight': '0',
                'prefixAlign': 'right',
                'width': '182px',
                'placeholder': '请输入',
                'maxlength': 10,
                'prefixWidth': '140px'
              },
              'key': '1611220411000_93992',
              'his_id': 'zhixingzhe'
            }, {
              'score': 0,
              'mConfig': {},
              'type': 'input',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_heduizhe',
                'hasPadding': true,
                'prefixColor': '#666666',
                'prefix': '核对者：',
                'prefixPaddingRight': '0',
                'prefixAlign': 'right',
                'width': '182px',
                'placeholder': '请输入',
                'maxlength': 10,
                'prefixWidth': '140px'
              },
              'key': '1611220411000_20342',
              'his_id': 'heduizhe'
            }],
            'flex': 1,
            'justify': 'flex-start',
            'width': '',
            'childWidth': 'auto',
            'align': 'flex-start',
            'gapTB': '5px',
            'direction': 'column'
          }],
          'type': 'grid',
          'value': '',
          'config': {
            'margin': '12px 0 0',
            'borderColor': '#EEF0F6',
            'borderWidth': '1px',
            'borderStyle': 'solid'
          },
          'key': '1611220411000_59656'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '',
        'childWidth': '100%',
        'align': 'flex-start',
        'gapTB': '',
        'direction': 'column'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0',
        'borderStyle': 'solid'
      },
      'key': '1611220411000_79965'
    }, {
      'columns': [{
        'padding': '0',
        'gapLR': '0',
        'children': [{
          'type': 'text',
          'value': '',
          'config': {
            'color': '#000',
            'weight': '',
            'fontSize': '16px',
            'label': '输血中监测',
            'align': 'left'
          },
          'key': '1611220411000_43439'
        }, {
          'columns': [{
            'padding': '7px 0',
            'gapLR': '0',
            'children': [{
              'score': 0,
              'type': 'date',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_shuxuekaishishijian',
                'clearable': false,
                'prefixColor': '#666666',
                'readonly': false,
                'prefix': '输血开始时间：',
                'prefixPaddingRight': '0',
                'prefixAlign': 'right',
                'width': '182px',
                'disabled': false,
                'placeholder': '请选择',
                'type': 'time',
                'prefixWidth': '140px',
                'showFormat': 'HH:mm'
              },
              'key': '1611738200000_61155',
              'his_id': 'shuxueshijian1'
            }, {
              'score': 0,
              'type': 'date',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_celiangshijian2',
                'clearable': false,
                'prefixColor': '#666666',
                'readonly': false,
                'prefix': '测量时间：',
                'prefixPaddingRight': '0',
                'prefixAlign': 'right',
                'width': '182px',
                'disabled': false,
                'placeholder': '请选择',
                'type': 'time',
                'prefixWidth': '140px',
                'showFormat': 'HH:mm'
              },
              'key': '1611220411000_60132',
              'his_id': 'time2'
            }, {
              'score': 0,
              'options': [{
                'score': 0,
                'id': '1611220411000_518-0',
                'label': '拒测'
              }, {
                'score': 0,
                'id': '1611220411000_518-1',
                'label': '外出'
              }, {
                'score': 0,
                'id': '1611220411000_518-2',
                'label': '请假'
              }, {
                'score': 0,
                'id': '1611220411000_518-3',
                'label': '不升'
              }],
              'type': 'select',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_tiwen2',
                'filterable': true,
                'prefixColor': '#666666',
                'prefix': '体温：',
                'prefixAlign': 'right',
                'suffix': '℃',
                'suffixWidth': '50px',
                'suffixPaddingLeft': '12px',
                'suffixColor': '#333333',
                'prefixPaddingRight': '0',
                'suffixAlign': 'left',
                'width': '182px',
                'placeholder': '请输入',
                'prefixWidth': '140px',
                'allowCreate': true
              },
              'key': '1611220411000_518',
              'his_id': 'tiwen2'
            }, {
              'score': 0,
              'mConfig': {},
              'type': 'input',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_maibo2',
                'hasPadding': true,
                'prefixColor': '#666666',
                'prefix': '脉搏：',
                'prefixAlign': 'right',
                'suffix': '次/分',
                'suffixWidth': '50px',
                'suffixPaddingLeft': '12px',
                'suffixColor': '#333333',
                'prefixPaddingRight': '0',
                'suffixAlign': 'left',
                'width': '182px',
                'placeholder': '请输入',
                'maxlength': 10,
                'prefixWidth': '140px'
              },
              'key': '1611220411000_14023',
              'his_id': 'maibo2'
            }, {
              'score': 0,
              'mConfig': {},
              'type': 'input',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_huxi2',
                'hasPadding': true,
                'prefixColor': '#666666',
                'prefix': '呼吸：',
                'prefixAlign': 'right',
                'suffix': '次/分',
                'suffixWidth': '50px',
                'suffixPaddingLeft': '12px',
                'suffixColor': '#333333',
                'prefixPaddingRight': '0',
                'suffixAlign': 'left',
                'width': '182px',
                'placeholder': '请输入',
                'maxlength': 10,
                'prefixWidth': '140px'
              },
              'key': '1611220411000_97439',
              'his_id': 'huxi2'
            }, {
              'score': 0,
              'mConfig': {},
              'type': 'input',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_shousuoya2',
                'hasPadding': true,
                'prefixColor': '#666666',
                'prefix': '收缩压：',
                'prefixAlign': 'right',
                'suffix': 'mmol/L',
                'suffixWidth': '50px',
                'suffixPaddingLeft': '12px',
                'suffixColor': '#333333',
                'prefixPaddingRight': '0',
                'suffixAlign': 'left',
                'width': '182px',
                'placeholder': '请输入',
                'maxlength': 10,
                'prefixWidth': '140px'
              },
              'key': '1611299655000_67328',
              'his_id': 'shousuoya2'
            }, {
              'score': 0,
              'mConfig': {},
              'type': 'input',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_shuzhangya2',
                'hasPadding': true,
                'prefixColor': '#666666',
                'prefix': '舒张压：',
                'prefixAlign': 'right',
                'suffix': 'mmol/L',
                'suffixWidth': '50px',
                'suffixPaddingLeft': '12px',
                'suffixColor': '#333333',
                'prefixPaddingRight': '0',
                'suffixAlign': 'left',
                'width': '182px',
                'placeholder': '请输入',
                'maxlength': 10,
                'prefixWidth': '140px'
              },
              'key': '1611299694000_26347',
              'his_id': 'shuzhangya2'
            }],
            'flex': 1,
            'justify': 'flex-start',
            'width': '',
            'childWidth': 'auto',
            'align': 'flex-start',
            'gapTB': '5px',
            'direction': 'column'
          }],
          'type': 'grid',
          'value': '',
          'config': {
            'margin': '12px 0 0',
            'borderColor': '#EEF0F6',
            'borderWidth': '1px',
            'borderStyle': 'solid'
          },
          'key': '1611220411000_71713'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '',
        'childWidth': '100%',
        'align': 'flex-start',
        'gapTB': '',
        'direction': 'column'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0',
        'borderStyle': 'solid'
      },
      'key': '1611220411000_88180'
    }, {
      'columns': [{
        'padding': '0',
        'gapLR': '0',
        'children': [{
          'type': 'text',
          'value': '',
          'config': {
            'color': '#000',
            'weight': '',
            'fontSize': '16px',
            'label': '输血中监测',
            'align': 'left'
          },
          'key': '1611220411000_39436'
        }, {
          'columns': [{
            'padding': '7px 0',
            'gapLR': '0',
            'children': [{
              'score': 0,
              'type': 'date',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_shuxuekaishishijian2',
                'clearable': false,
                'prefixColor': '#666666',
                'readonly': false,
                'prefix': '输血开始时间：',
                'prefixPaddingRight': '0',
                'prefixAlign': 'right',
                'width': '182px',
                'disabled': false,
                'placeholder': '请选择',
                'type': 'time',
                'prefixWidth': '140px',
                'showFormat': 'HH:mm'
              },
              'key': '1611738545000_90325',
              'his_id': 'shuxueshijian2'
            }, {
              'score': 0,
              'type': 'date',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_celiangshijian3',
                'clearable': false,
                'prefixColor': '#666666',
                'readonly': false,
                'prefix': '测量时间：',
                'prefixPaddingRight': '0',
                'prefixAlign': 'right',
                'width': '182px',
                'disabled': false,
                'placeholder': '请选择',
                'type': 'time',
                'prefixWidth': '140px',
                'showFormat': 'HH:mm'
              },
              'key': '1611220411000_29433',
              'his_id': 'time3'
            }, {
              'score': 0,
              'options': [{
                'score': 0,
                'id': '1611220411000_64287-0',
                'label': '拒测'
              }, {
                'score': 0,
                'id': '1611220411000_64287-1',
                'label': '外出'
              }, {
                'score': 0,
                'id': '1611220411000_64287-2',
                'label': '请假'
              }, {
                'score': 0,
                'id': '1611220411000_64287-3',
                'label': '不升'
              }],
              'type': 'select',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_tiwen3',
                'filterable': true,
                'prefixColor': '#666666',
                'prefix': '体温：',
                'prefixAlign': 'right',
                'suffix': '℃',
                'suffixWidth': '50px',
                'suffixPaddingLeft': '12px',
                'suffixColor': '#333333',
                'prefixPaddingRight': '0',
                'suffixAlign': 'left',
                'width': '182px',
                'placeholder': '请输入',
                'prefixWidth': '140px',
                'allowCreate': true
              },
              'key': '1611220411000_64287',
              'his_id': 'tiwen3'
            }, {
              'score': 0,
              'mConfig': {},
              'type': 'input',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_maibo3',
                'hasPadding': true,
                'prefixColor': '#666666',
                'prefix': '脉搏：',
                'prefixAlign': 'right',
                'suffix': '次/分',
                'suffixWidth': '50px',
                'suffixPaddingLeft': '12px',
                'suffixColor': '#333333',
                'prefixPaddingRight': '0',
                'suffixAlign': 'left',
                'width': '182px',
                'placeholder': '请输入',
                'maxlength': 10,
                'prefixWidth': '140px'
              },
              'key': '1611220411000_74303',
              'his_id': 'maibo3'
            }, {
              'score': 0,
              'mConfig': {},
              'type': 'input',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_huxi3',
                'hasPadding': true,
                'prefixColor': '#666666',
                'prefix': '呼吸：',
                'prefixAlign': 'right',
                'suffix': '次/分',
                'suffixWidth': '50px',
                'suffixPaddingLeft': '12px',
                'suffixColor': '#333333',
                'prefixPaddingRight': '0',
                'suffixAlign': 'left',
                'width': '182px',
                'placeholder': '请输入',
                'maxlength': 10,
                'prefixWidth': '140px'
              },
              'key': '1611220411000_5235',
              'his_id': 'huxi3'
            }, {
              'score': 0,
              'mConfig': {},
              'type': 'input',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_shousuoya3',
                'hasPadding': true,
                'prefixColor': '#666666',
                'prefix': '收缩压：',
                'prefixAlign': 'right',
                'suffix': 'mmol/L',
                'suffixWidth': '50px',
                'suffixPaddingLeft': '12px',
                'suffixColor': '#333333',
                'prefixPaddingRight': '0',
                'suffixAlign': 'left',
                'width': '182px',
                'placeholder': '请输入',
                'maxlength': 10,
                'prefixWidth': '140px'
              },
              'key': '1611299779000_46355',
              'his_id': 'shousuoya3'
            }, {
              'score': 0,
              'mConfig': {},
              'type': 'input',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_shuzhangya3',
                'hasPadding': true,
                'prefixColor': '#666666',
                'prefix': '舒张压：',
                'prefixAlign': 'right',
                'suffix': 'mmol/L',
                'suffixWidth': '50px',
                'suffixPaddingLeft': '12px',
                'suffixColor': '#333333',
                'prefixPaddingRight': '0',
                'suffixAlign': 'left',
                'width': '182px',
                'placeholder': '请输入',
                'maxlength': 10,
                'prefixWidth': '140px'
              },
              'key': '1611299769000_93064',
              'his_id': 'shuzhangya3'
            }],
            'flex': 1,
            'justify': 'flex-start',
            'width': '',
            'childWidth': 'auto',
            'align': 'flex-start',
            'gapTB': '5px',
            'direction': 'column'
          }],
          'type': 'grid',
          'value': '',
          'config': {
            'margin': '12px 0 0',
            'borderColor': '#EEF0F6',
            'borderWidth': '1px',
            'borderStyle': 'solid'
          },
          'key': '1611220411000_54381'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '',
        'childWidth': '100%',
        'align': 'flex-start',
        'gapTB': '',
        'direction': 'column'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0',
        'borderStyle': 'solid'
      },
      'key': '1611220411000_92467'
    }, {
      'columns': [{
        'padding': '0',
        'gapLR': '0',
        'children': [{
          'type': 'text',
          'value': '',
          'config': {
            'color': '#000',
            'weight': '',
            'fontSize': '16px',
            'label': '输血不良反应观察',
            'align': 'left'
          },
          'key': '1611220411000_66447'
        }, {
          'columns': [{
            'padding': '7px 0',
            'gapLR': '0',
            'children': [{
              'score': 0,
              'options': [{
                'score': 0,
                'id': '1611220411000_11847-0',
                'label': '无'
              }, {
                'score': 0,
                'id': '1611220411000_11847-1',
                'label': '有'
              }],
              'type': 'select',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_youwubuliangfanying',
                'filterable': true,
                'prefixColor': '#666666',
                'prefix': '有无不良反应：',
                'prefixPaddingRight': '0',
                'prefixAlign': 'right',
                'width': '182px',
                'placeholder': '请输入',
                'prefixWidth': '140px'
              },
              'key': '1611220411000_11847',
              'his_id': 'buliangfanying'
            }, {
              'score': 0,
              'type': 'date',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_fashengshijian',
                'clearable': false,
                'prefixColor': '#666666',
                'readonly': false,
                'prefix': '发生时间：',
                'prefixPaddingRight': '0',
                'prefixAlign': 'right',
                'width': '182px',
                'disabled': true,
                'keyDisabled': '1611220411000_11847-1',
                'placeholder': '请选择',
                'type': 'time',
                'prefixWidth': '140px',
                'showFormat': 'HH:mm'
              },
              'key': '1611220411000_26705',
              'his_id': 'fashengshijian'
            }, {
              'score': 0,
              'options': [{
                'score': 0,
                'id': '1611220411000_36255-0',
                'label': '过敏反应'
              }, {
                'score': 0,
                'id': '1611220411000_36255-1',
                'label': '发热反应'
              }, {
                'score': 0,
                'id': '1611220411000_36255-2',
                'label': '溶血反应'
              }, {
                'score': 0,
                'id': '1611220411000_36255-3',
                'label': '其他反应'
              }],
              'type': 'select',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_buliangfanyingleixing',
                'filterable': true,
                'disabled': true,
                'keyDisabled': '1611220411000_11847-1',
                'prefixColor': '#666666',
                'prefix': '不良反应类型：',
                'prefixPaddingRight': '0',
                'prefixAlign': 'right',
                'width': '182px',
                'placeholder': '请输入',
                'prefixWidth': '140px'
              },
              'key': '1611220411000_36255',
              'his_id': 'buliangfanyingleixing'
            }, {
              'score': 0,
              'mConfig': {},
              'type': 'input',
              'value': '',
              'config': {
                'uniId': 'guanchadan_shuxueguanchadan_qitafanying',
                'hasPadding': true,
                'prefixColor': '#666666',
                'prefix': '其他反应：',
                'prefixAlign': 'right',
                'prefixPaddingRight': '0',
                'suffixAlign': 'left',
                'width': '182px',
                'placeholder': '请输入',
                'maxlength': 10,
                'prefixWidth': '140px',
                'disabled': true,
                'keyDisabled': '1611220411000_11847-1',
              },
              'key': '1611302873000_25942',
              'his_id': 'qitafanying'
            }],
            'flex': 1,
            'justify': 'flex-start',
            'width': '',
            'childWidth': 'auto',
            'align': 'flex-start',
            'gapTB': '5px',
            'direction': 'column'
          }],
          'type': 'grid',
          'value': '',
          'config': {
            'margin': '12px 0 0',
            'borderColor': '#EEF0F6',
            'borderWidth': '1px',
            'borderStyle': 'solid'
          },
          'key': '1611220411000_35974'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '',
        'childWidth': '100%',
        'align': 'flex-start',
        'gapTB': '',
        'direction': 'column'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0',
        'borderStyle': 'solid'
      },
      'key': '1611220411000_26728'
    }, {
      'columns': [{
        'padding': '0',
        'gapLR': '0',
        'children': [{
          'score': 0,
          'options': [{
            'score': 0,
            'id': '1611220411000_62574-0',
            'label': 'A'
          }, {
            'score': 0,
            'id': '1611220411000_62574-1',
            'label': 'B'
          }, {
            'score': 0,
            'id': '1611220411000_62574-2',
            'label': 'O'
          }, {
            'score': 0,
            'id': '1611220411000_62574-3',
            'label': 'AB'
          }],
          'type': 'select',
          'value': '',
          'config': {
            'uniId': 'guanchadan_shuxueguanchadan_ABOxuexing',
            'filterable': true,
            'prefixColor': '#666666',
            'prefix': 'ABO血型：',
            'prefixPaddingRight': '0',
            'prefixAlign': 'right',
            'width': '182px',
            'placeholder': '请输入',
            'prefixWidth': '140px'
          },
          'key': '1611220411000_62574',
          'his_id': 'ABOxuexing'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '',
        'childWidth': 'auto',
        'align': 'flex-start',
        'gapTB': '0',
        'direction': 'column'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#EEF0F6',
        'borderWidth': '0px',
        'borderStyle': 'solid'
      },
      'key': '1611220411000_26156'
    }, {
      'columns': [{
        'padding': '0',
        'gapLR': '0',
        'children': [{
          'score': 0,
          'options': [{
            'score': 0,
            'id': '1611220411000_54980-0',
            'label': '+（阳性）'
          }, {
            'score': 0,
            'id': '1611220411000_54980-1',
            'label': '-（阴性）'
          }],
          'type': 'select',
          'value': '',
          'config': {
            'uniId': 'guanchadan_shuxueguanchadan_RHxuexing',
            'filterable': true,
            'prefixColor': '#666666',
            'prefix': 'RH血型：',
            'prefixPaddingRight': '0',
            'prefixAlign': 'right',
            'width': '182px',
            'placeholder': '请输入',
            'prefixWidth': '140px'
          },
          'key': '1611220411000_54980',
          'his_id': 'RHxuexing'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '',
        'childWidth': 'auto',
        'align': 'flex-start',
        'gapTB': '0',
        'direction': 'column'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#EEF0F6',
        'borderWidth': '0px',
        'borderStyle': 'solid'
      },
      'key': '1611220411000_55346'
    }, {
      'columns': [{
        'padding': '0',
        'gapLR': '0',
        'children': [{
          'score': 0,
          'options': [{
            'score': 0,
            'id': '1611220411000_657-0',
            'label': '无'
          }, {
            'score': 0,
            'id': '1611220411000_657-1',
            'label': '有'
          }],
          'type': 'select',
          'value': '',
          'config': {
            'uniId': 'guanchadan_shuxueguanchadan_shuxueshi',
            'filterable': true,
            'prefixColor': '#666666',
            'prefix': '输血史：',
            'prefixPaddingRight': '0',
            'prefixAlign': 'right',
            'width': '182px',
            'placeholder': '请输入',
            'prefixWidth': '140px'
          },
          'key': '1611220411000_657',
          'his_id': 'shuxueshi'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '',
        'childWidth': 'auto',
        'align': 'flex-start',
        'gapTB': '0',
        'direction': 'column'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#EEF0F6',
        'borderWidth': '0px',
        'borderStyle': 'solid'
      },
      'key': '1611220411000_83181'
    }, {
      'columns': [{
        'padding': '0',
        'gapLR': '0',
        'children': [{
          'score': 0,
          'options': [{
            'score': 0,
            'id': '1611220411000_34672-0',
            'label': '无'
          }, {
            'score': 0,
            'id': '1611220411000_34672-1',
            'label': '有'
          }],
          'type': 'select',
          'value': '',
          'config': {
            'uniId': 'guanchadan_shuxueguanchadan_shuxuebuliangfanyingshi',
            'filterable': true,
            'prefixColor': '#666666',
            'prefix': '输血不良反应史：',
            'prefixPaddingRight': '0',
            'prefixAlign': 'right',
            'width': '182px',
            'placeholder': '请输入',
            'prefixWidth': '140px'
          },
          'key': '1611220411000_34672',
          'his_id': 'fanyingshi'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '',
        'childWidth': 'auto',
        'align': 'flex-start',
        'gapTB': '0',
        'direction': 'column'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#EEF0F6',
        'borderWidth': '0px',
        'borderStyle': 'solid'
      },
      'key': '1611220411000_60163'
    }, {
      'columns': [{
        'padding': '0',
        'gapLR': '0',
        'children': [{
          'score': 0,
          'options': [{
            'score': 0,
            'id': '1611220411000_69952-0',
            'label': '发热反应'
          }, {
            'score': 0,
            'id': '1611220411000_69952-1',
            'label': '过敏反应'
          }, {
            'score': 0,
            'id': '1611220411000_69952-2',
            'label': '溶血反应'
          }, {
            'score': 0,
            'id': '1611220411000_69952-3',
            'label': '其他反应'
          }],
          'type': 'select',
          'value': '',
          'config': {
            'uniId': 'guanchadan_shuxueguanchadan_buliangfanyingleixing2',
            'filterable': true,
            'prefixColor': '#666666',
            'prefix': '不良反应类型：',
            'prefixPaddingRight': '0',
            'prefixAlign': 'right',
            'width': '182px',
            'placeholder': '请输入',
            'prefixWidth': '140px',
            'clearable': true
          },
          'key': '1611220411000_69952',
          'his_id': 'buliangfanying2'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '',
        'childWidth': 'auto',
        'align': 'flex-start',
        'gapTB': '0',
        'direction': 'column'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#EEF0F6',
        'borderWidth': '0px',
        'borderStyle': 'solid'
      },
      'key': '1611220411000_24987'
    }],
    'flex': 1,
    'justify': 'flex-start',
    'width': '',
    'childWidth': '399px',
    'align': 'flex-start',
    'gapTB': '15px',
    'direction': 'column'
  }],
  'type': 'grid',
  'value': '',
  'config': {
    'borderColor': '#ddd',
    'borderWidth': '0',
    'borderStyle': 'solid'
  },
  'key': '1611220411000_95321'
}]
