// 转科患者交接记录单
export const changeDepartmentData =
	[{
	  'columns': [{
	    'padding': '0',
	    'gapLR': '0',
	    'children': [{
	      'type': 'date',
	      'value': '',
	      'config': {
	        'prefix': '时间:',
	        'prefixWidth': '90px',
	        'noCenter': true,
	        'borderLine': true,
	        'readonly': false,
	        'prefixAlign': 'right',
	        'width': '240px',
	        'disabled': false,
	        'type': 'datetime',
		  	'showFormat': 'yyyy-MM-dd'
	      },
	      'key': '1601364493000_365518'
	    }],
	    'flex': '1',
	    'justify': 'flex-start',
	    'width': '',
	    'childWidth': '',
	    'align': '',
	    'gapTB': '',
	    'direction': 'row'
	  }],
	  'type': 'grid',
	  'value': '',
	  'config': {
	    'borderColor': '#ddd',
	    'borderWidth': '0',
	    'borderStyle': 'solid'
	  },
	  'key': '1616038293000_6117'
	}, {
	  'columns': [{
	    'padding': '10px',
	    'gapLR': '0',
	    'children': [{
	      'type': 'text',
	      'value': '',
	      'config': {
	        'weight': '60px',
	        'label': 'S',
	        'align': 'center'
	      },
	      'key': '1616038293000_6518'
	    }, {
	      'type': 'text',
	      'value': '',
	      'config': {
	        'weight': '60px',
	        'label': '现状',
	        'align': 'center'
	      },
	      'key': '1616038293000_84394'
	    }],
	    'flex': '',
	    'justify': 'center',
	    'width': '60px',
	    'childWidth': '',
	    'align': 'center',
	    'gapTB': '0',
	    'direction': 'column'
	  }, {
	    'padding': '0 0 0 5px',
	    'gapLR': '0',
	    'children': [{
	      'score': 0,
	      'mConfig': {},
	      'type': 'input',
	      'value': '',
	      'config': {
	        'borderLine': true,
	        'readonly': false,
	        'prefix': '诊断:',
	        'prefixAlign': 'left',
	        'width': '860px',
	        'disabled': false,
	        'inputType': 'textarea',
	        'prefixWidth': '60px'
	      },
	      'key': '1606284173000_32570'
	    }],
	    'flex': 1,
	    'justify': 'flex-start',
	    'width': '',
	    'childWidth': '',
	    'align': 'center',
	    'gapTB': '',
	    'direction': 'row'
	  }],
	  'type': 'grid',
	  'value': '',
	  'config': {
	    'borderColor': '#ddd',
	    'borderWidth': '1px',
	    'borderStyle': 'solid'
	  },
	  'key': '1616038293000_99413'
	}, {
	  'columns': [{
	    'padding': '0 10px',
	    'gapLR': '0',
	    'children': [{
	      'type': 'text',
	      'value': '',
	      'config': {
	        'weight': '100px',
	        'label': '生命体征',
	        'align': 'center'
	      },
	      'key': '1616038293000_94052'
	    }],
	    'flex': '',
	    'justify': 'center',
	    'width': '60px',
	    'childWidth': '',
	    'align': 'center',
	    'gapTB': '0',
	    'direction': 'column'
	  }, {
	    'padding': '',
	    'gapLR': '5px',
	    'children': [{
	      'score': 0,
	      'mConfig': {},
	      'type': 'input',
	      'value': '',
	      'config': {
	        'borderLine': true,
	        'readonly': false,
	        'prefix': 'T:',
	        'width': '100px',
	        'prefixAlign': 'left',
	        'disabled': false,
	        'inputType': 'text',
	        'prefixWidth': '15px',
	        'suffix': '℃',
	        'noCenter': true,
	        'suffixPaddingLeft': '16px'
	      },
	      'key': '1616038293000_83556'
	    }, {
	      'score': 0,
	      'mConfig': {},
	      'type': 'input',
	      'value': '',
	      'config': {
	        'borderLine': true,
	        'readonly': false,
	        'prefix': 'P:',
	        'prefixAlign': 'right',
	        'width': '100px',
	        'disabled': false,
	        'inputType': 'text',
	        'prefixWidth': '70px',
	        'suffix': '次/分',
	        'noCenter': true,
	        'suffixPaddingLeft': '16px'
	      },
	      'key': '1616038293000_39623'
	    }, {
	      'score': 0,
	      'mConfig': {},
	      'type': 'input',
	      'value': '',
	      'config': {
	        'borderLine': true,
	        'readonly': false,
	        'prefix': 'BP:',
	        'width': '91px',
	        'prefixAlign': 'left',
	        'disabled': false,
	        'inputType': 'text',
	        'prefixWidth': '25px',
	        'suffix': 'mmHg',
	        'noCenter': true
	      },
	      'key': '1616038293000_9095'
	    }, {
	      'score': 0,
	      'mConfig': {},
	      'type': 'input',
	      'value': '',
	      'config': {
	        'borderLine': true,
	        'readonly': false,
	        'prefix': 'R:',
	        'prefixAlign': 'right',
	        'width': '100px',
	        'disabled': false,
	        'inputType': 'text',
	        'prefixWidth': '42px',
	        'suffix': '次/分',
	        'noCenter': true,
	        'suffixPaddingLeft': '16px'
	      },
	      'key': '1616038293000_28053'
	    }],
	    'flex': '1',
	    'justify': 'flex-start',
	    'width': '',
	    'childWidth': '',
	    'align': 'flex-start',
	    'gapTB': '5px',
	    'direction': 'row'
	  }, {
	    'padding': '',
	    'gapLR': '5px',
	    'children': [{
	      'score': 0,
	      'mConfig': {},
	      'type': 'input',
	      'value': '',
	      'config': {
	        'borderLine': true,
	        'readonly': false,
	        'prefix': 'T:',
	        'width': '100px',
	        'prefixAlign': 'left',
	        'disabled': false,
	        'inputType': 'text',
	        'prefixWidth': '15px',
	        'suffix': '℃',
	        'noCenter': true,
	        'suffixPaddingLeft': '16px'
	      },
	      'key': '1616038293000_21251'
	    }, {
	      'score': 0,
	      'mConfig': {},
	      'type': 'input',
	      'value': '',
	      'config': {
	        'borderLine': true,
	        'readonly': false,
	        'prefix': 'P:',
	        'prefixAlign': 'right',
	        'width': '100px',
	        'disabled': false,
	        'inputType': 'text',
	        'prefixWidth': '70px',
	        'suffix': '次/分',
	        'noCenter': true,
	        'suffixPaddingLeft': '16px'
	      },
	      'key': '1616038293000_17817'
	    }, {
	      'score': 0,
	      'mConfig': {},
	      'type': 'input',
	      'value': '',
	      'config': {
	        'borderLine': true,
	        'readonly': false,
	        'prefix': 'BP:',
	        'width': '91px',
	        'prefixAlign': 'left',
	        'disabled': false,
	        'inputType': 'text',
	        'prefixWidth': '25px',
	        'suffix': 'mmHg',
	        'noCenter': true
	      },
	      'key': '1616038293000_42766'
	    }, {
	      'score': 0,
	      'mConfig': {},
	      'type': 'input',
	      'value': '',
	      'config': {
	        'borderLine': true,
	        'readonly': false,
	        'prefix': 'R:',
	        'prefixAlign': 'right',
	        'width': '100px',
	        'disabled': false,
	        'inputType': 'text',
	        'prefixWidth': '42px',
	        'suffix': '次/分',
	        'noCenter': true,
	        'suffixPaddingLeft': '16px'
	      },
	      'key': '1616038293000_64072'
	    }],
	    'flex': '1',
	    'justify': 'flex-start',
	    'width': '',
	    'childWidth': '',
	    'align': 'flex-start',
	    'gapTB': '5px',
	    'direction': 'row'
	  }],
	  'type': 'grid',
	  'value': '',
	  'config': {
	    'borderColor': '#ddd',
	    'borderWidth': '1px',
	    'borderStyle': 'solid'
	  },
	  'key': '1616038293000_56696'
	}, {
	  'mConfig': {},
	  'columns': [{
	    'padding': '0 10px',
	    'gapLR': '0',
	    'children': [{
	      'mConfig': {},
	      'type': 'text',
	      'value': '',
	      'config': {
	        'weight': '',
	        'label': 'B',
	        'align': 'center'
	      },
	      'key': '1616038293000_40429'
	    }, {
	      'mConfig': {},
	      'type': 'text',
	      'value': '',
	      'config': {
	        'weight': '',
	        'label': '背景',
	        'align': 'center'
	      },
	      'key': '1616038293000_5735'
	    }],
	    'flex': '',
	    'justify': 'center',
	    'width': '60px',
	    'childWidth': '',
	    'align': 'center',
	    'gapTB': '0',
	    'direction': 'column'
	  }, {
	    'padding': '',
	    'gapLR': '0',
	    'children': [{
	      'columns': [{
	        'padding': '',
	        'gapLR': '5px',
	        'children': [{
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_59453-0',
	            'label': '无'
	          }, {
	            'score': 0,
	            'id': '1616038293000_59453-1',
	            'label': '有',
	            'children': [{
	              'score': 0,
	              'type': 'input',
	              'value': '',
	              'config': {
	                'borderLine': true,
	                'readonly': false,
	                'disabled': false,
	                'inputType': 'input',
	                'isRadio': true,
	                'width': '275px',
									'keyDisabled': '1616038293000_59453-1',
	              },
	              'key': '1616038293000_68163'
	            }]
	          }],
	          'score': 0,
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'prefix': '过敏史',
	            'prefixWidth': '60px',
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox',
	            'isRadio': true
	          },
	          'key': '1616038293000_59453'
	        }, {
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_85874-0',
	            'label': '无'
	          }, {
	            'score': 0,
	            'id': '1616038293000_85874-1',
	            'label': '有',
	            'children': [{
	              'score': 0,
	              'type': 'input',
	              'value': '',
	              'config': {
	                'borderLine': true,
	                'readonly': false,
	                'disabled': false,
	                'inputType': 'input',
	                'width': '275px',
				    			'keyDisabled': '1616038293000_85874-1',
	              },
	              'key': '1616038293000_53613'
	            }]
	          }],
	          'score': 0,
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'prefix': '既往史',
	            'prefixWidth': '60px',
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox',
	            'isRadio': true
	          },
	          'key': '1616038293000_85874'
	        }],
	        'flex': '1',
	        'justify': 'flex-start',
	        'width': '',
	        'childWidth': '',
	        'align': '',
	        'gapTB': '5px',
	        'direction': 'row'
	      }],
	      'type': 'grid',
	      'value': '',
	      'config': {
	        'borderColor': '#ddd',
	        'borderWidth': '1px',
	        'borderStyle': 'solid'
	      },
	      'key': '1616038293000_82567'
	    }, {
	      'columns': [{
	        'padding': '0',
	        'gapLR': '5px',
	        'children': [{
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_88062-0',
	            'label': '无'
	          }, {
	            'score': 0,
	            'id': '1616038293000_88062-1',
	            'label': '口服药',
	            'children': [{
	              'score': 0,
	              'type': 'input',
	              'value': '',
	              'config': {
	                'borderLine': true,
	                'readonly': false,
	                'disabled': false,
	                'inputType': 'input',
	                'width': '216px',
				    			'keyDisabled': '1616038293000_88062-1',
	              },
	              'key': '1616038293000_4317'
	            }]
	          }, {
	            'score': 0,
	            'id': '1616038293000_88062-2',
	            'label': '静脉用药',
	            'children': [{
	              'score': 0,
	              'type': 'input',
	              'value': '',
	              'config': {
	                'borderLine': true,
	                'readonly': false,
	                'disabled': false,
	                'inputType': 'input',
	                'width': '271px',
				    			'keyDisabled': '1616038293000_88062-2',
	              },
	              'key': '1616038293000_75981'
	            }]
	          }],
	          'score': 0,
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox',
	            'prefix': '药物:',
	            'prefixWidth': '60px',
			    		'noAlignCenter': true
	          },
	          'key': '1616038293000_88062'
	        }, {
	          'score': 0,
	          'mConfig': {},
	          'type': 'input',
	          'value': '',
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'prefix': '正在使用的药物:',
	            'prefixAlign': 'right',
	            'width': '160px',
	            'disabled': false,
	            'inputType': 'text',
	            'prefixWidth': '214px',
	            'suffix': ''
	          },
	          'key': '1616038293000_15397'
	        }, {
	          'score': 0,
	          'mConfig': {},
	          'type': 'input',
	          'value': '',
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'prefix': '其他:',
	            'prefixAlign': 'right',
	            'width': '250px',
	            'disabled': false,
	            'inputType': 'text',
	            'prefixWidth': '125px',
	            'suffix': ''
	          },
	          'key': '1616038293000_8028'
	        }, {
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_37770-0',
	            'label': '无'
	          }, {
	            'score': 0,
	            'id': '1616038293000_37770-1',
	            'label': '有',
	            'children': [{
	              'score': 0,
	              'type': 'input',
	              'value': '',
	              'config': {
	                'borderLine': true,
	                'readonly': false,
	                'disabled': false,
	                'inputType': 'input',
	                'width': '187px',
				    			'keyDisabled': '1616038293000_37770-1',
	              },
	              'key': '1616038293000_93878'
	            }]
	          }],
	          'score': 0,
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox',
	            'isRadio': true,
	            'prefix': '血制品:',
	            'prefixWidth': '75px'
	          },
	          'key': '1616038293000_37770'
	        }, {
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_11756-0',
	            'label': '完好'
	          }, {
	            'score': 0,
	            'id': '1616038293000_11756-1',
	            'label': '异常',
	            'children': [{
	              'score': 0,
	              'type': 'input',
	              'value': '',
	              'config': {
	                'borderLine': true,
	                'readonly': false,
	                'disabled': false,
	                'inputType': 'input',
	                'width': '157px',
				    			'keyDisabled': '1616038293000_11756-1',
	              },
	              'key': '1616038293000_43282'
	            }]
	          }],
	          'score': 0,
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox',
	            'isRadio': true,
	            'prefix': '皮肤:',
	            'prefixWidth': '75px'
	          },
	          'key': '1616038293000_11756'
	        }, {
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_28754-0',
	            'label': '住院病历'
	          }, {
	            'score': 0,
	            'id': '1616038293000_28754-1',
	            'label': '门诊病历'
	          }, {
	            'score': 0,
	            'id': '1616038293000_28754-2',
	            'label': '医学影像资料',
	            'children': [{
	              'score': 0,
	              'type': 'input',
	              'value': '',
	              'config': {
	                'borderLine': true,
	                'readonly': false,
	                'disabled': false,
	                'inputType': 'input',
	                'width': '100px',
	                'suffix': '张',
									'keyDisabled': '1616038293000_28754-2',
	              },
	              'key': '1616038293000_23809'
	            }]
	          }],
	          'score': 0,
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox',
	            'prefix': '物品:',
	            'prefixWidth': '75px',
			    		'noAlignCenter': true
	          },
	          'key': '1616038293000_28754'
	        }],
	        'flex': '1',
	        'justify': 'flex-start',
	        'width': '100%',
	        'childWidth': '',
	        'align': '',
	        'gapTB': '5px',
	        'direction': 'row'
	      }, {
	        'padding': '0',
	        'gapLR': '5px',
	        'children': [{
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_60898-0',
	            'label': '无'
	          }, {
	            'score': 0,
	            'id': '1616038293000_60898-1',
	            'label': '口服药',
	            'children': [{
	              'score': 0,
	              'type': 'input',
	              'value': '',
	              'config': {
	                'borderLine': true,
	                'readonly': false,
	                'disabled': false,
	                'inputType': 'input',
	                'width': '216px',
				    			'keyDisabled': '1616038293000_60898-1',
	              },
	              'key': '1616038293000_98913'
	            }]
	          }, {
	            'score': 0,
	            'id': '1616038293000_60898-2',
	            'label': '静脉用药',
	            'children': [{
	              'score': 0,
	              'type': 'input',
	              'value': '',
	              'config': {
	                'borderLine': true,
	                'readonly': false,
	                'disabled': false,
	                'inputType': 'input',
	                'width': '271px',
				    			'keyDisabled': '1616038293000_60898-2',
	              },
	              'key': '1616038293000_14308'
	            }]
	          }],
	          'score': 0,
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox',
	            'prefix': '药物:',
	            'prefixWidth': '60px',
			    		'noAlignCenter': true
	          },
	          'key': '1616038293000_60898'
	        }, {
	          'score': 0,
	          'mConfig': {},
	          'type': 'input',
	          'value': '',
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'prefix': '正在使用的药物:',
	            'prefixAlign': 'right',
	            'width': '160px',
	            'disabled': false,
	            'inputType': 'text',
	            'prefixWidth': '214px',
	            'suffix': ''
	          },
	          'key': '1616038293000_16513'
	        }, {
	          'score': 0,
	          'mConfig': {},
	          'type': 'input',
	          'value': '',
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'prefix': '其他:',
	            'prefixAlign': 'right',
	            'width': '250px',
	            'disabled': false,
	            'inputType': 'text',
	            'prefixWidth': '125px',
	            'suffix': ''
	          },
	          'key': '1616038293000_2369'
	        }, {
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_90224-0',
	            'label': '无'
	          }, {
	            'score': 0,
	            'id': '1616038293000_90224-1',
	            'label': '有',
	            'children': [{
	              'score': 0,
	              'type': 'input',
	              'value': '',
	              'config': {
	                'borderLine': true,
	                'readonly': false,
	                'disabled': false,
	                'inputType': 'input',
	                'width': '187px',
				   			  'keyDisabled': '1616038293000_90224-1',
	              },
	              'key': '1616038293000_40918'
	            }]
	          }],
	          'score': 0,
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox',
	            'isRadio': true,
	            'prefix': '血制品:',
	            'prefixWidth': '75px'
	          },
	          'key': '1616038293000_90224'
	        }, {
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_92894-0',
	            'label': '完好'
	          }, {
	            'score': 0,
	            'id': '1616038293000_92894-1',
	            'label': '异常',
	            'children': [{
	              'score': 0,
	              'type': 'input',
	              'value': '',
	              'config': {
	                'borderLine': true,
	                'readonly': false,
	                'disabled': false,
	                'inputType': 'input',
	                'width': '157px',
				    			'keyDisabled': '1616038293000_92894-1',
	              },
	              'key': '1616038293000_11545'
	            }]
	          }],
	          'score': 0,
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox',
	            'prefix': '皮肤:',
	            'prefixWidth': '75px',
	            'isRadio': true,
	          },
	          'key': '1616038293000_92894'
	        }, {
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_96909-0',
	            'label': '住院病历'
	          }, {
	            'score': 0,
	            'id': '1616038293000_96909-1',
	            'label': '门诊病历'
	          }, {
	            'score': 0,
	            'id': '1616038293000_96909-2',
	            'label': '医学影像资料',
	            'children': [{
	              'score': 0,
	              'type': 'input',
	              'value': '',
	              'config': {
	                'borderLine': true,
	                'readonly': false,
	                'disabled': false,
	                'inputType': 'input',
	                'width': '100px',
	                'suffix': '张',
				    			'keyDisabled': '1616038293000_96909-2',
	              },
	              'key': '1616038293000_63241'
	            }]
	          }],
	          'score': 0,
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox',
	            'prefix': '物品:',
	            'prefixWidth': '75px',
			    		'noAlignCenter': true
	          },
	          'key': '1616038293000_96909'
	        }],
	        'flex': '1',
	        'justify': 'flex-start',
	        'width': '100%',
	        'childWidth': '',
	        'align': 'flex-start',
	        'gapTB': '5px',
	        'direction': 'row'
	      }],
	      'type': 'grid',
	      'value': '',
	      'config': {
	        'borderColor': '#ddd',
	        'borderWidth': '1px',
	        'borderStyle': 'solid'
	      },
	      'key': '1616038293000_85817'
	    }],
	    'flex': '1',
	    'justify': '',
	    'width': '100%',
	    'childWidth': '100%',
	    'height': '100%',
	    'align': '',
	    'gapTB': '0',
	    'direction': 'row'
	  }],
	  'type': 'grid',
	  'value': '',
	  'config': {
	    'borderColor': '#ddd',
	    'borderWidth': '1px',
	    'borderStyle': 'solid'
	  },
	  'key': '1616038293000_94996'
	}, {
	  'mConfig': {},
	  'columns': [{
	    'padding': '0 10px',
	    'gapLR': '0',
	    'children': [{
	      'mConfig': {},
	      'type': 'text',
	      'value': '',
	      'config': {
	        'weight': '',
	        'label': 'A',
	        'align': 'center'
	      },
	      'key': '1616038293000_37302'
	    }, {
	      'mConfig': {},
	      'type': 'text',
	      'value': '',
	      'config': {
	        'weight': '',
	        'label': '评估',
	        'align': 'center'
	      },
	      'key': '1616038293000_13491'
	    }],
	    'flex': '',
	    'justify': 'center',
	    'width': '60px',
	    'childWidth': '',
	    'align': 'center',
	    'gapTB': '0',
	    'direction': 'column'
	  }, {
	    'padding': '',
	    'gapLR': '0',
	    'children': [{
	      'columns': [{
	        'padding': '5px',
	        'gapLR': '',
	        'children': [{
	          'mConfig': {},
	          'type': 'text',
	          'value': '',
	          'config': {
	            'width': '',
	            'weight': '',
	            'label': '意识:',
	            'align': 'left'
	          },
	          'key': '1616038293000_77163'
	        }, {
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_10360-0',
	            'label': '清醒'
	          }, {
	            'score': 0,
	            'id': '1616038293000_10360-1',
	            'label': '嗜睡'
	          }, {
	            'score': 0,
	            'id': '1616038293000_10360-3',
	            'label': '昏睡'
	          }, {
	            'score': 0,
	            'id': '1616038293000_10360-4',
	            'label': '浅昏迷'
	          }, {
	            'score': 0,
	            'id': '1616038293000_10360-5',
	            'label': '深昏迷'
	          }],
	          'score': 0,
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox'
	          },
	          'key': '1616038293000_10360'
	        }, {
	          'mConfig': {},
	          'type': 'text',
	          'value': '',
	          'config': {
	            'width': '400px',
	            'weight': '',
	            'label': '瞳孔:',
	            'align': 'left'
	          },
	          'key': '1616038293000_23530'
	        }, {
	          'score': 0,
	          'type': 'input',
	          'value': '',
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'input',
	            'prefix': '左',
	            'prefixWidth': '20px',
	            'width': '50px',
	            'suffix': 'mm'
	          },
	          'key': '1616038293000_70616'
	        }, {
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_65804-0',
	            'label': '灵敏'
	          }, {
	            'score': 0,
	            'id': '1616038293000_65804-1',
	            'label': '迟钝'
	          }, {
	            'score': 0,
	            'id': '1616038293000_65804-2',
	            'label': '消失'
	          }],
	          'score': 0,
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'prefix': '反应:',
	            'prefixWidth': '80px',
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox',
	            'isRadio': true,
	            'prefixAlign': 'right'
	          },
	          'key': '1616038293000_65804'
	        }, {
	          'score': 0,
	          'type': 'input',
	          'value': '',
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'input',
	            'prefix': '右',
	            'prefixWidth': '20px',
	            'width': '50px',
	            'suffix': 'mm'
	          },
	          'key': '1616038293000_90383'
	        }, {
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_87238-0',
	            'label': '灵敏'
	          }, {
	            'score': 0,
	            'id': '1616038293000_87238-1',
	            'label': '迟钝'
	          }, {
	            'score': 0,
	            'id': '1616038293000_87238-2',
	            'label': '消失'
	          }],
	          'score': 0,
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'prefix': '反应:',
	            'prefixWidth': '80px',
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox',
	            'isRadio': true,
	            'prefixAlign': 'right'
	          },
	          'key': '1616038293000_87238'
	        }, {
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_87939-0',
	            'label': '无'
	          }, {
	            'score': 0,
	            'id': '1616038293000_87939-1',
	            'label': '有(',
	            'children': [{
	              'options': [{
	                'score': 0,
	                'id': '1616038293000_22135-0',
	                'label': '鼻塞给氧'
	              }, {
	                'score': 0,
	                'id': '1616038293000_22135-1',
	                'label': '面罩给氧'
	              }, {
	                'score': 0,
	                'id': '1616038293000_22135-2',
	                'label': '呼吸囊'
	              }, {
	                'score': 0,
	                'id': '1616038293000_22135-3',
	                'label': '其他',
	                'children': [{
	                  'score': 0,
	                  'type': 'input',
	                  'value': '',
	                  'config': {
	                    'width': '200px',
	                    'prefix': '',
	                    'prefixWidth': '',
	                    'borderLine': true,
	                    'readonly': false,
	                    'disabled': false,
	                    'inputType': 'input',
	                    'suffix': ')',
	                    'prefixAlign': '',
					    				'keyDisabled': '1616038293000_87939-1,1616038293000_22135-3'
	                  },
	                  'key': '1616038293000_87773'
	                }]
	              }],
	              'score': 0,
	              'type': 'checkbox',
	              'value': [],
	              'config': {
	                'borderLine': true,
	                'readonly': false,
	                'disabled': false,
	                'inputType': 'checkbox',
				   				'keyDisabled': '1616038293000_87939-1',
	              },
	              'key': '1616038293000_22135'
	            }]
	          }],
	          'score': 0,
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'prefix': '给氧:',
	            'prefixWidth': '60px',
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox',
	            'isRadio': true,
	            'prefixAlign': 'left'
	          },
	          'key': '1616038293000_87939'
	        }, {
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_36715-0',
	            'label': '无'
	          }, {
	            'score': 0,
	            'id': '1616038293000_36715-1',
	            'label': '有(',
	            'children': [{
	              'options': [{
	                'score': 0,
	                'id': '1616038293000_85701-0',
	                'label': '周围静脉',
	                'marginRight': '5px'
	              }, {
	                'score': 0,
	                'id': '1616038293000_85701-1',
	                'label': 'PICC',
	                'marginRight': '5px'
	              }, {
	                'score': 0,
	                'id': '1616038293000_85701-2',
	                'label': '中心静脉插管 ）',
	                'marginRight': '5px'
	              }],
	              'score': 0,
	              'type': 'checkbox',
	              'value': [],
	              'config': {
	                'borderLine': true,
	                'readonly': false,
	                'disabled': false,
	                'inputType': 'checkbox',
				    			'keyDisabled': '1616038293000_36715-1',
	              },
	              'key': '1616038293000_85701'
	            }]
	          }],
	          'score': 0,
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'prefix': '静脉通路:',
	            'prefixWidth': '90px',
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox',
	            'isRadio': true,
	            'prefixAlign': 'left'
	          },
	          'key': '1616038293000_36715'
	        }, {
	          'score': 0,
	          'type': 'input',
	          'value': '',
	          'config': {
	            'width': '260px',
	            'prefix': '静脉留置针部位1:',
	            'prefixWidth': '150px',
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'input',
	            'isRadio': true,
	            'suffix': '',
	            'prefixAlign': ''
	          },
	          'key': '1616038293000_82248'
	        }, {
	          'score': 0,
	          'type': 'text',
	          'value': '',
	          'config': {
	            'width': '136px',
	            'label': '（ ',
	            'align': 'right',
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'text',
	            'isRadio': true,
	            'suffix': '',
	            'prefixAlign': ''
	          },
	          'key': '1616038293000_69038'
	        }, {
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_49035-0',
	            'label': '封闭'
	          }, {
	            'score': 0,
	            'id': '1616038293000_49035-1',
	            'label': '通畅'
	          }, {
	            'score': 0,
	            'id': '1616038293000_49035-2',
	            'label': '不通畅'
	          }],
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox',
	            'isRadio': true
	          },
	          'key': '1616038293000_49035'
	        }, {
	          'score': 0,
	          'type': 'text',
	          'value': '',
	          'config': {
	            'width': '10px',
	            'label': '）',
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'text',
	            'isRadio': true,
	            'suffix': '',
	            'prefixAlign': ''
	          },
	          'key': '1616038293000_65869'
	        }, {
	          'score': 0,
	          'type': 'input',
	          'value': '',
	          'config': {
	            'width': '260px',
	            'prefix': '静脉留置针部位2:',
	            'prefixWidth': '150px',
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'input',
	            'isRadio': true,
	            'suffix': '',
	            'prefixAlign': ''
	          },
	          'key': '1616038293000_84612'
	        }, {
	          'score': 0,
	          'type': 'text',
	          'value': '',
	          'config': {
	            'width': '136px',
	            'label': '（ ',
	            'align': 'right',
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'text',
	            'isRadio': true,
	            'suffix': '',
	            'prefixAlign': ''
	          },
	          'key': '1616038293000_42743'
	        }, {
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_79446-0',
	            'label': '封闭'
	          }, {
	            'score': 0,
	            'id': '1616038293000_79446-1',
	            'label': '通畅'
	          }, {
	            'score': 0,
	            'id': '1616038293000_79446-2',
	            'label': '不通畅'
	          }],
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox',
	            'isRadio': true
	          },
	          'key': '1616038293000_79446'
	        }, {
	          'score': 0,
	          'type': 'text',
	          'value': '',
	          'config': {
	            'width': '10px',
	            'label': '）',
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'text',
	            'isRadio': true,
	            'suffix': '',
	            'prefixAlign': ''
	          },
	          'key': '1616038293000_39706'
	        }, {
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_18869-0',
	            'label': '正常'
	          }, {
	            'score': 0,
	            'id': '1616038293000_18869-1',
	            'label': '肿胀'
	          }, {
	            'score': 0,
	            'id': '1616038293000_18869-2',
	            'label': '外渗'
	          }, {
	            'score': 0,
	            'id': '1616038293000_18869-3',
	            'label': '其他',
	            'children': [{
	              'score': 0,
	              'type': 'input',
	              'value': '',
	              'config': {
	                'width': '200px',
	                'prefix': '',
	                'prefixWidth': '',
	                'borderLine': true,
	                'readonly': false,
	                'disabled': false,
	                'inputType': 'input',
	                'suffix': '',
	                'prefixAlign': '',
				    			'keyDisabled': '1616038293000_18869-3',
	              },
	              'key': '1616038293000_19516'
	            }]
	          }],
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox',
	            'prefix': '局部情况:',
	            'prefixWidth': '90px',
							'noAlignCenter': true
	          },
	          'key': '1616038293000_18869'
	        }, {
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_58154-0',
	            'label': '无'
	          }, {
	            'score': 0,
	            'id': '1616038293000_58154-1',
	            'label': '有(',
	            'children': [{
	              'options': [{
	                'score': 0,
	                'id': '1616038293000_89803-0',
	                'label': '胃管深度',
									'children': [{
										'score': 0,
										'type': 'input',
										'value': '',
										'config': {
											'width': '70px',
											'prefix': '',
											'prefixWidth': '',
											'borderLine': true,
											'readonly': false,
											'disabled': false,
											'inputType': 'input',
											'isRadio': true,
											'suffix': 'mm',
											'prefixAlign': '',
											'keyDisabled': '1616038293000_58154-1,1616038293000_89803-0',
										},
										'key': '1616038293000_7966'
	                }]
	              }, {
	                'score': 0,
	                'id': '1616038293000_89803-2',
	                'label': '尿管'
	              }, {
	                'score': 0,
	                'id': '1616038293000_89803-3',
	                'label': '引流管'
	              }, {
	                'score': 0,
	                'id': '1616038293000_89803-4',
	                'label': '其他',
	                'children': [{
	                  'score': 0,
	                  'type': 'input',
	                  'value': '',
	                  'config': {
	                    'width': '200px',
	                    'prefix': '',
	                    'prefixWidth': '',
	                    'borderLine': true,
	                    'readonly': false,
	                    'disabled': false,
	                    'inputType': 'input',
	                    'suffix': ')',
	                    'prefixAlign': '',
					    				'keyDisabled': '1616038293000_58154-1,1616038293000_89803-4'
	                  },
	                  'key': '1616038293000_16903'
	                }]
	              }],
	              'type': 'checkbox',
	              'value': [],
	              'config': {
	                'borderLine': true,
	                'readonly': false,
	                'disabled': false,
	                'inputType': 'checkbox',
	                'prefix': '',
	                'prefixWidth': '',
				    			'keyDisabled': '1616038293000_58154-1',
	              },
	              'key': '1616038293000_89803'
	            }]
	          }],
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox',
	            'isRadio': true,
	            'prefix': '管道:',
	            'prefixWidth': '90px',
							'noAlignCenter': true
	          },
	          'key': '1616038293000_58154'
	        }],
	        'flex': '1',
	        'justify': 'flex-start',
	        'width': '',
	        'childWidth': '',
	        'align': 'center',
	        'gapTB': '5px',
	        'direction': 'row'
	      }, {
	        'padding': '5px',
	        'gapLR': '',
	        'children': [{
	          'mConfig': {},
	          'type': 'text',
	          'value': '',
	          'config': {
	            'width': '',
	            'weight': '',
	            'label': '意识:',
	            'align': 'left'
	          },
	          'key': '1616038293000_77673'
	        }, {
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_94922-0',
	            'label': '清醒'
	          }, {
	            'score': 0,
	            'id': '1616038293000_94922-1',
	            'label': '嗜睡'
	          }, {
	            'score': 0,
	            'id': '1616038293000_94922-2',
	            'label': '昏睡'
	          }, {
	            'score': 0,
	            'id': '1616038293000_94922-4',
	            'label': '浅昏迷'
	          }, {
	            'score': 0,
	            'id': '1616038293000_94922-5',
	            'label': '深昏迷'
	          }],
	          'score': 0,
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox'
	          },
	          'key': '1616038293000_94922'
	        }, {
	          'mConfig': {},
	          'type': 'text',
	          'value': '',
	          'config': {
	            'width': '400px',
	            'weight': '',
	            'label': '瞳孔:',
	            'align': 'left'
	          },
	          'key': '1616038293000_96844'
	        }, {
	          'score': 0,
	          'type': 'input',
	          'value': '',
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'input',
	            'prefix': '左',
	            'prefixWidth': '20px',
	            'width': '50px',
	            'suffix': 'mm'
	          },
	          'key': '1616038293000_26593'
	        }, {
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_53549-0',
	            'label': '灵敏'
	          }, {
	            'score': 0,
	            'id': '1616038293000_53549-1',
	            'label': '迟钝'
	          }, {
	            'score': 0,
	            'id': '1616038293000_53549-2',
	            'label': '消失'
	          }],
	          'score': 0,
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'prefix': '反应:',
	            'prefixWidth': '80px',
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox',
	            'isRadio': true,
	            'prefixAlign': 'right'
	          },
	          'key': '1616038293000_53549'
	        }, {
	          'score': 0,
	          'type': 'input',
	          'value': '',
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'input',
	            'prefix': '右',
	            'prefixWidth': '20px',
	            'width': '50px',
	            'suffix': 'mm'
	          },
	          'key': '1616038293000_77069'
	        }, {
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_35027-0',
	            'label': '灵敏'
	          }, {
	            'score': 0,
	            'id': '1616038293000_35027-1',
	            'label': '迟钝'
	          }, {
	            'score': 0,
	            'id': '1616038293000_35027-2',
	            'label': '消失'
	          }],
	          'score': 0,
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'prefix': '反应:',
	            'prefixWidth': '80px',
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox',
	            'isRadio': true,
	            'prefixAlign': 'right'
	          },
	          'key': '1616038293000_35027'
	        }, {
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_42424-0',
	            'label': '无'
	          }, {
	            'score': 0,
	            'id': '1616038293000_42424-1',
	            'label': '有(',
	            'children': [{
	              'options': [{
	                'score': 0,
	                'id': '1616038293000_63101-0',
	                'label': '鼻塞给氧'
	              }, {
	                'score': 0,
	                'id': '1616038293000_63101-1',
	                'label': '面罩给氧'
	              }, {
	                'score': 0,
	                'id': '1616038293000_63101-2',
	                'label': '呼吸囊'
	              }, {
	                'score': 0,
	                'id': '1616038293000_63101-3',
	                'label': '其他',
	                'children': [{
	                  'score': 0,
	                  'type': 'input',
	                  'value': '',
	                  'config': {
	                    'width': '200px',
	                    'prefix': '',
	                    'prefixWidth': '',
	                    'borderLine': true,
	                    'readonly': false,
	                    'disabled': false,
	                    'inputType': 'input',
	                    'suffix': ')',
	                    'prefixAlign': '',
					    				'keyDisabled': '1616038293000_42424-1,1616038293000_63101-3'
	                  },
	                  'key': '1616038293000_5795'
	                }]
	              }],
	              'score': 0,
	              'type': 'checkbox',
	              'value': [],
	              'config': {
	                'borderLine': true,
	                'readonly': false,
	                'disabled': false,
	                'inputType': 'checkbox',
									'keyDisabled': '1616038293000_42424-1'
	              },
	              'key': '1616038293000_63101'
	            }]
	          }],
	          'score': 0,
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'prefix': '给氧:',
	            'prefixWidth': '60px',
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox',
	            'isRadio': true,
	            'prefixAlign': 'left'
	          },
	          'key': '1616038293000_42424'
	        }, {
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_86178-0',
	            'label': '无'
	          }, {
	            'score': 0,
	            'id': '1616038293000_86178-1',
	            'label': '有(',
	            'children': [{
	              'options': [{
	                'score': 0,
	                'id': '1616038293000_40285-0',
	                'label': '周围静脉',
	                'marginRight': '5px'
	              }, {
	                'score': 0,
	                'id': '1616038293000_40285-1',
	                'label': 'PICC',
	                'marginRight': '5px'
	              }, {
	                'score': 0,
	                'id': '1616038293000_40285-2',
	                'label': '中心静脉插管 ）',
	                'marginRight': '5px'
	              }],
	              'score': 0,
	              'type': 'checkbox',
	              'value': [],
	              'config': {
	                'borderLine': true,
	                'readonly': false,
	                'disabled': false,
	                'inputType': 'checkbox',
				    			'keyDisabled': '1616038293000_86178-1',
	              },
	              'key': '1616038293000_40285'
	            }]
	          }],
	          'score': 0,
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'prefix': '静脉通路:',
	            'prefixWidth': '90px',
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox',
	            'isRadio': true,
	            'prefixAlign': 'left'
	          },
	          'key': '1616038293000_86178'
	        }, {
	          'score': 0,
	          'type': 'input',
	          'value': '',
	          'config': {
	            'width': '260px',
	            'prefix': '静脉留置针部位1:',
	            'prefixWidth': '150px',
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'input',
	            'suffix': '',
	            'prefixAlign': ''
	          },
	          'key': '1616038293000_67967'
	        }, {
	          'score': 0,
	          'type': 'text',
	          'value': '',
	          'config': {
	            'width': '136px',
	            'label': '（ ',
	            'align': 'right',
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'text',
	            'suffix': '',
	            'prefixAlign': ''
	          },
	          'key': '1616038293000_71217'
	        }, {
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_46376-0',
	            'label': '封闭'
	          }, {
	            'score': 0,
	            'id': '1616038293000_46376-1',
	            'label': '通畅'
	          }, {
	            'score': 0,
	            'id': '1616038293000_46376-2',
	            'label': '不通畅'
	          }],
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox',
	            'isRadio': true
	          },
	          'key': '1616038293000_46376'
	        }, {
	          'score': 0,
	          'type': 'text',
	          'value': '',
	          'config': {
	            'width': '10px',
	            'label': '）',
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'text',
	            'suffix': '',
	            'prefixAlign': ''
	          },
	          'key': '1616038293000_87638'
	        }, {
	          'score': 0,
	          'type': 'input',
	          'value': '',
	          'config': {
	            'width': '260px',
	            'prefix': '静脉留置针部位2:',
	            'prefixWidth': '150px',
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'input',
	            'suffix': '',
	            'prefixAlign': ''
	          },
	          'key': '1616038293000_21067'
	        }, {
	          'score': 0,
	          'type': 'text',
	          'value': '',
	          'config': {
	            'width': '136px',
	            'label': '（ ',
	            'align': 'right',
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'text',
	            'suffix': '',
	            'prefixAlign': ''
	          },
	          'key': '1616038293000_80515'
	        }, {
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_66227-0',
	            'label': '封闭'
	          }, {
	            'score': 0,
	            'id': '1616038293000_66227-1',
	            'label': '通畅'
	          }, {
	            'score': 0,
	            'id': '1616038293000_66227-2',
	            'label': '不通畅'
	          }],
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox',
	            'isRadio': true
	          },
	          'key': '1616038293000_66227'
	        }, {
	          'score': 0,
	          'type': 'text',
	          'value': '',
	          'config': {
	            'width': '10px',
	            'label': '）',
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'text',
	            'suffix': '',
	            'prefixAlign': ''
	          },
	          'key': '1616038293000_46145'
	        }, {
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_42331-0',
	            'label': '正常'
	          }, {
	            'score': 0,
	            'id': '1616038293000_42331-1',
	            'label': '肿胀'
	          }, {
	            'score': 0,
	            'id': '1616038293000_42331-2',
	            'label': '外渗'
	          }, {
	            'score': 0,
	            'id': '1616038293000_42331-3',
	            'label': '其他',
	            'children': [{
	              'score': 0,
	              'type': 'input',
	              'value': '',
	              'config': {
	                'width': '200px',
	                'prefix': '',
	                'prefixWidth': '',
	                'borderLine': true,
	                'readonly': false,
	                'disabled': false,
	                'inputType': 'input',
	                'suffix': '',
	                'prefixAlign': '',
				    			'keyDisabled': '1616038293000_42331-3',
	              },
	              'key': '1616038293000_29621'
	            }]
	          }],
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox',
	            'prefix': '局部情况:',
	            'prefixWidth': '90px',
							'noAlignCenter': true
	          },
	          'key': '1616038293000_42331'
	        }, {
	          'options': [{
	            'score': 0,
	            'id': '1616038293000_37162-0',
	            'label': '无'
	          }, {
	            'score': 0,
	            'id': '1616038293000_37162-1',
	            'label': '有(',
	            'children': [{
	              'options': [{
	                'score': 0,
	                'id': '1616038293000_88324-0',
	                'label': '胃管深度',
									'children': [{
										'score': 0,
										'type': 'input',
										'value': '',
										'config': {
											'width': '70px',
											'prefix': '',
											'prefixWidth': '',
											'borderLine': true,
											'readonly': false,
											'disabled': false,
											'inputType': 'input',
											'isRadio': true,
											'suffix': 'mm',
											'prefixAlign': '',
											'keyDisabled': '1616038293000_37162-1,1616038293000_88324-0'
										},
										'key': '1616038293000_42064'
									}]
	              }, {
	                'score': 0,
	                'id': '1616038293000_88324-2',
	                'label': '尿管'
	              }, {
	                'score': 0,
	                'id': '1616038293000_88324-3',
	                'label': '引流管'
	              }, {
	                'score': 0,
	                'id': '1616038293000_88324-4',
	                'label': '其他',
	                'children': [{
	                  'score': 0,
	                  'type': 'input',
	                  'value': '',
	                  'config': {
	                    'width': '200px',
	                    'prefix': '',
	                    'prefixWidth': '',
	                    'borderLine': true,
	                    'readonly': false,
	                    'disabled': false,
	                    'inputType': 'input',
	                    'suffix': ')',
	                    'prefixAlign': '',
					    				'keyDisabled': '1616038293000_37162-1,1616038293000_88324-4',
	                  },
	                  'key': '1616038293000_35640'
	                }]
	              }],
	              'type': 'checkbox',
	              'value': [],
	              'config': {
	                'borderLine': true,
	                'readonly': false,
	                'disabled': false,
	                'inputType': 'checkbox',
	                'prefix': '',
	                'prefixWidth': '',
				    			'keyDisabled': '1616038293000_37162-1',
	              },
	              'key': '1616038293000_88324'
	            }]
	          }],
	          'type': 'checkbox',
	          'value': [],
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'disabled': false,
	            'inputType': 'checkbox',
	            'isRadio': true,
	            'prefix': '管道:',
	            'prefixWidth': '90px',
							'noAlignCenter': true
	          },
	          'key': '1616038293000_37162'
	        }],
	        'flex': '1',
	        'justify': 'flex-start',
	        'width': '',
	        'childWidth': '',
	        'align': 'center',
	        'gapTB': '5px',
	        'direction': 'row'
	      }],
	      'type': 'grid',
	      'value': '',
	      'config': {
	        'borderColor': '#ddd',
	        'borderWidth': '1px',
	        'borderStyle': 'solid'
	      },
	      'key': '1616038293000_17033'
	    }],
	    'flex': '1',
	    'justify': '',
	    'width': '100%',
	    'childWidth': '100%',
	    'height': '100%',
	    'align': 'center',
	    'gapTB': '',
	    'direction': 'row'
	  }],
	  'type': 'grid',
	  'value': '',
	  'config': {
	    'borderColor': '#ddd',
	    'borderWidth': '1px',
	    'borderStyle': 'solid'
	  },
	  'key': '1616038293000_3347'
	}, {
	  'mConfig': {},
	  'columns': [{
	    'padding': '0 10px',
	    'gapLR': '0',
	    'children': [{
	      'mConfig': {},
	      'type': 'text',
	      'value': '',
	      'config': {
	        'weight': '',
	        'label': 'R',
	        'align': 'center'
	      },
	      'key': '1616038293000_12092'
	    }, {
	      'mConfig': {},
	      'type': 'text',
	      'value': '',
	      'config': {
	        'weight': '',
	        'label': '建议',
	        'align': 'center'
	      },
	      'key': '1616038293000_3247'
	    }],
	    'flex': '',
	    'justify': 'center',
	    'width': '60px',
	    'childWidth': '',
	    'align': 'center',
	    'gapTB': '0',
	    'direction': 'column'
	  }, {
	    'padding': '2px 0',
	    'gapLR': '5px',
	    'children': [{
	      'options': [{
	        'score': 0,
	        'id': '1616038293000_68015-0',
	        'label': '无',
	        'children': [{
	          'score': 0,
	          'type': 'input',
	          'value': '',
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'prefix': '',
	            'prefixAlign': 'left',
	            'width': '400px',
	            'disabled': false,
	            'inputType': 'text',
	            'prefixWidth': '60px',
	            'noCenter': true,
			    'keyDisabled': '1616038293000_68015-0',
	          },
	          'key': '1616038293000_4534'
	        }]
	      }, {
	        'score': 0,
	        'id': '1616038293000_68015-1',
	        'label': '有',
	        'children': [{
	          'score': 0,
	          'type': 'input',
	          'value': '',
	          'config': {
	            'borderLine': true,
	            'readonly': false,
	            'prefix': '',
	            'prefixAlign': 'left',
	            'width': '400px',
	            'disabled': false,
	            'inputType': 'text',
	            'prefixWidth': '60px',
	            'noCenter': true,
			    		'keyDisabled': '1616038293000_68015-1',
	          },
	          'key': '1616038293000_58017'
	        }]
	      }],
	      'score': 0,
	      'type': 'checkbox',
	      'value': [],
	      'config': {
	        'borderLine': true,
	        'readonly': false,
	        'disabled': false,
	        'inputType': 'checkbox',
	        'isRadio': true
	      },
	      'key': '1616038293000_68015'
	    }, {
	      'options': [{
	        'score': 0,
	        'id': '1616038293000_6146-0',
	        'label': '生命体征的变化'
	      }, {
	        'score': 0,
	        'id': '1616038293000_6146-1',
	        'label': '管道引流情况'
	      }, {
	        'score': 0,
	        'id': '1616038293000_6146-2',
	        'label': '皮肤受压情况'
	      }],
	      'score': 0,
	      'type': 'checkbox',
	      'value': [],
	      'config': {
	        'borderLine': true,
	        'readonly': false,
	        'disabled': false,
	        'inputType': 'checkbox',
	        'marginRight': '114px'
	      },
	      'key': '1616038293000_6146'
	    }, {
	      'score': 0,
	      'type': 'input',
	      'value': '',
	      'config': {
	        'borderLine': true,
	        'readonly': false,
	        'prefix': '其他:',
	        'prefixAlign': 'left',
	        'width': '860px',
	        'disabled': false,
	        'inputType': 'text',
	        'prefixWidth': '60px',
	        'noCenter': true
	      },
	      'key': '1616038293000_53509'
	    }],
	    'flex': 1,
	    'justify': '',
	    'width': '',
	    'childWidth': '',
	    'align': 'center',
	    'gapTB': '1px',
	    'direction': 'row'
	  }],
	  'type': 'grid',
	  'value': '',
	  'config': {
	    'borderColor': '#ddd',
	    'borderWidth': '1px',
	    'borderStyle': 'solid'
	  },
	  'key': '1616038293000_9621'
	}, {
	  'mConfig': {
	    'title': '交接人员',
	    'isCollapse': true
	  },
	  'columns': [{
	    'padding': '0 10px',
	    'gapLR': '0',
	    'children': [{
	      'mConfig': {
	        'hidden': true
	      },
	      'type': 'text',
	      'value': '',
	      'config': {
	        'weight': '',
	        'label': '交接人员',
	        'align': 'center'
	      },
	      'key': '1616038293000_62920'
	    }],
	    'flex': '',
	    'justify': '',
	    'width': '60px',
	    'childWidth': 'auto',
	    'align': 'center',
	    'gapTB': '0',
	    'direction': 'row'
	  }, {
	    'padding': '2px 5px',
	    'gapLR': '0',
	    'children': [{
	      'score': 0,
	      'mConfig': {},
	      'type': 'input',
	      'value': '',
	      'config': {
	        'borderLine': true,
	        'readonly': false,
	        'prefix': '转出科室:',
	        'prefixAlign': 'left',
	        'width': '200px',
	        'disabled': false,
	        'inputType': 'input',
	        'prefixWidth': '90px',
			'noCenter': true,
	      },
	      'key': '1601364493000_61933'
	    }, {
			'score': 0,
			'mConfig': {},
			'type': 'input',
			'value': '',
			'config': {
				'borderLine': true,
				'readonly': false,
				'prefix': '护士签名:',
				'prefixAlign': 'left',
				'width': '200px',
				'disabled': false,
				'inputType': 'input',
				'prefixWidth': '90px',
				'noCenter': true,
			},
			'key': '1601364493000_9461'
		}, {
	      'score': 0,
	      'mConfig': {},
	      'type': 'date',
	      'value': '',
	      'config': {
	        'borderLine': true,
	        'readonly': false,
	        'prefix': '日期时间:',
	        'prefixAlign': 'left',
	        'width': '275px',
	        'disabled': false,
	        'type': 'datetime',
	        'prefixWidth': '90px',
		    'noCenter': true,
		    'showFormat': 'yyyy-MM-dd HH:mm'
	      },
	      'key': '1601364493000_35518'
	    }],
	    'flex': 1,
	    'justify': 'flex-start',
	    'width': '',
	    'childWidth': '100%',
	    'align': 'flex-start',
	    'gapTB': '1px',
	    'direction': 'row'
	  }, {
	    'padding': '2px 5px',
	    'gapLR': '0',
	    'children': [{
	      'score': 0,
	      'mConfig': {},
	      'type': 'input',
	      'value': '',
	      'config': {
	        'borderLine': true,
	        'readonly': false,
	        'prefix': '转入科室:',
	        'prefixAlign': 'left',
	        'width': '200px',
	        'disabled': false,
	        'inputType': 'input',
	        'prefixWidth': '90px',
		    'noCenter': true,
	      },
	      'key': '1616038293000_88864'
	    }, {
			'score': 0,
			'mConfig': {},
			'type': 'input',
			'value': '',
			'config': {
				'borderLine': true,
				'readonly': false,
				'prefix': '护士签名:',
				'prefixAlign': 'left',
				'width': '200px',
				'disabled': false,
				'inputType': 'input',
				'prefixWidth': '90px',
				'noCenter': true,
			},
			'key': '1616038293000_10899'
		}, {
			'score': 0,
			'mConfig': {},
			'type': 'date',
			'value': '',
			'config': {
				'borderLine': true,
				'readonly': false,
				'prefix': '日期时间:',
				'prefixAlign': 'left',
				'width': '275px',
				'disabled': false,
				'type': 'datetime',
				'prefixWidth': '90px',
				'noCenter': true,
				'showFormat': 'yyyy-MM-dd HH:mm'
			},
			'key': '1616038293000_2902'
		}],
	    'flex': 1,
	    'justify': 'flex-start',
	    'width': '',
	    'childWidth': '100%',
	    'align': '',
	    'gapTB': '1px',
	    'direction': 'row'
	  }],
	  'type': 'grid',
	  'value': '',
	  'config': {
	    'borderColor': '#ddd',
	    'borderWidth': '1px',
	    'borderStyle': 'solid'
	  },
	  'key': '1616038293000_84730'
	}]
