// 术前护理评估
export const OperationData1 = [{
  'columns': [{
    'padding': '10px',
    'gapLR': '',
    'children': [{
      'columns': [{
        'padding': '0',
        'gapLR': '0',
        'children': [{
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefixWeight': 'bold',
            'borderLine': true,
            'readonly': false,
            'prefix': 'T',
            'prefixAlign': 'left',
            'suffixAlign': 'left',
            'width': '70px',
            'disabled': false,
            'inputType': 'text',
            'suffix': '℃',
            'prefixWidth': '10px',
            'suffixWidth': '20px'
          },
          'key': '1599793641000_51025'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefixWeight': 'bold',
            'borderLine': true,
            'readonly': false,
            'prefix': 'P',
            'prefixAlign': 'right',
            'suffixAlign': 'left',
            'width': '70px',
            'disabled': false,
            'inputType': 'text',
            'suffix': '次/分',
            'prefixWidth': '20px',
            'suffixWidth': '40px'
          },
          'key': '1599794101000_68002'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefixWeight': 'bold',
            'borderLine': true,
            'readonly': false,
            'prefix': 'R',
            'prefixAlign': 'right',
            'suffixAlign': 'left',
            'width': '70px',
            'disabled': false,
            'inputType': 'text',
            'suffix': '次/分',
            'prefixWidth': '20px',
            'suffixWidth': '40px'
          },
          'key': '1599794257000_55173'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefixWeight': 'bold',
            'borderLine': true,
            'readonly': false,
            'prefix': 'W',
            'prefixAlign': 'right',
            'suffixAlign': 'left',
            'width': '70px',
            'disabled': false,
            'inputType': 'text',
            'suffix': 'kg',
            'prefixWidth': '20px',
            'suffixWidth': '60px'
          },
          'key': '1599794347000_61133'
        }, {
          'score': 0,
          'type': 'date',
          'value': '',
          'config': {
            'readonly': false,
            'prefix': '测量时间',
            'prefixAlign': 'right',
            'width': '190px',
            'disabled': false,
            'placeholder': '',
            'type': 'datetime',
            'prefixWidth': '70px'
          },
          'key': '1599794507000_78647'
        }],
        'flex': 1,
        'justify': 'space-between',
        'width': '',
        'childWidth': 'auto',
        'align': 'center',
        'gapTB': '0',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0',
        'borderStyle': 'solid'
      },
      'key': '1599793969000_67940'
    }, {
      'score': 0,
      'type': 'date',
      'value': '',
      'config': {
        'prefixWeight': 'bold',
        'readonly': false,
        'prefix': '拟行手术时间：',
        'prefixAlign': 'left',
        'width': '190px',
        'disabled': false,
        'placeholder': '',
        'type': 'datetime',
        'prefixWidth': '120px'
      },
      'key': '1599795077000_67349'
    }, {
      'score': 0,
      'options': [{
        'score': 0,
        'id': '1599800246000_23943-1',
        'label': '局麻'
      }, {
        'score': 0,
        'id': '1599800246000_23943-2',
        'label': '全麻'
      }, {
        'score': 0,
        'id': '1599800246000_23943-3',
        'label': '硬膜外'
      }, {
        'score': 0,
        'id': '1599800246000_23943-4',
        'label': '颈丛'
      }, {
        'score': 0,
        'id': '1599800246000_23943-5',
        'label': '臂丛'
      }, {
        'score': 0,
        'children': [{
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': '',
            'prefixAlign': 'right',
            'width': '181px',
            'disabled': false,
            'placeholder': '',
            'prefixWidth': '75px'
          },
          'key': '1599800284000_80989'
        }],
        'id': '1599800246000_23943-6',
        'label': '其他'
      }],
      'type': 'checkbox',
      'value': [],
      'config': {
        'marginRight': '20px',
        'prefixWeight': 'bold',
        'prefix': '拟行麻醉方式：',
        'prefixAlign': 'left',
        'prefixWidth': '120px'
      },
      'key': '1599800246000_23943'
    }, {
      'columns': [{
        'padding': '0',
        'gapLR': '0',
        'children': [{
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefixWeight': 'bold',
            'borderLine': true,
            'readonly': false,
            'prefix': '诊断：',
            'prefixAlign': 'left',
            'suffixAlign': 'left',
            'width': '300px',
            'disabled': false,
            'inputType': 'text',
            'suffix': '',
            'prefixWidth': '80px',
            'suffixWidth': '20px'
          },
          'key': '1599800846000_81805'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefixWeight': 'bold',
            'borderLine': true,
            'readonly': false,
            'prefix': '拟行手术名称：',
            'prefixAlign': 'right',
            'suffixAlign': 'left',
            'width': '330px',
            'disabled': false,
            'inputType': 'text',
            'suffix': '',
            'prefixWidth': '120px',
            'suffixWidth': '40px'
          },
          'key': '1599800884000_80243'
        }],
        'flex': 1,
        'justify': 'space-between',
        'width': '',
        'childWidth': 'auto',
        'align': 'center',
        'gapTB': '0',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0',
        'borderStyle': 'solid'
      },
      'key': '1599800820000_78980'
    }, {
      'columns': [{
        'padding': '0',
        'gapLR': '0',
        'children': [{
          'score': 0,
          'options': [{
            'score': 0,
            'id': '1599801297000_27611-1',
            'label': '无'
          }, {
            'score': 0,
            'id': '1599801297000_27611-2',
            'label': '已执行'
          }, {
            'score': 0,
            'id': '1599801297000_27611-3',
            'label': '未执行'
          }],
          'type': 'checkbox',
          'value': [],
          'config': {
            'marginRight': '10px',
            'prefixWeight': 'bold',
            'prefix': '备皮：',
            'prefixAlign': 'left',
            'prefixWidth': '80px'
          },
          'key': '1599801297000_27611'
        }, {
          'score': 0,
          'options': [{
            'score': 0,
            'id': '1599801591000_51087-1',
            'label': '无'
          }, {
            'score': 0,
            'id': '1599801591000_51087-2',
            'label': '已执行'
          }, {
            'score': 0,
            'id': '1599801591000_51087-3',
            'label': '未执行'
          }],
          'type': 'checkbox',
          'value': [],
          'config': {
            'marginRight': '10px',
            'prefixWeight': 'bold',
            'prefix': '合血：',
            'prefixAlign': 'right',
            'prefixWidth': '70px'
          },
          'key': '1599801591000_51087'
        }, {
          'score': 0,
          'options': [{
            'score': 0,
            'id': '1599801714000_92424-1',
            'label': '已执行'
          }, {
            'score': 0,
            'id': '1599801714000_92424-2',
            'label': '未执行'
          }],
          'type': 'checkbox',
          'value': [],
          'config': {
            'marginRight': '10px',
            'prefixWeight': 'bold',
            'prefix': '卫生处置：',
            'prefixAlign': 'right',
            'prefixWidth': '120px'
          },
          'key': '1599801714000_92424'
        }],
        'flex': 1,
        'justify': 'space-start',
        'width': '',
        'childWidth': 'auto',
        'align': 'center',
        'gapTB': '0',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0',
        'borderStyle': 'solid'
      },
      'key': '1599801131000_8897'
    }, {
      'score': 0,
      'options': [{
        'score': 0,
        'id': '1599801972000_90808-1',
        'label': '无'
      }, {
        'score': 0,
        'children': [{
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': '药物1：',
            'prefixAlign': 'right',
            'suffixAlign': 'left',
            'width': '200px',
            'disabled': false,
            'inputType': 'textarea',
            'suffix': '',
            'prefixWidth': '70px',
            'suffixWidth': '40px'
          },
          'key': '1599802039000_53994'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': '药物2：',
            'prefixAlign': 'right',
            'suffixAlign': 'left',
            'width': '200px',
            'disabled': false,
            'inputType': 'textarea',
            'suffix': '',
            'prefixWidth': '70px',
            'suffixWidth': '40px'
          },
          'key': '1599802121000_41383'
        }],
        'id': '1599801972000_90808-2',
        'label': '有'
      }],
      'type': 'checkbox',
      'value': [],
      'config': {
        'prefixWeight': 'bold',
        'prefix': '皮试：',
        'prefixAlign': 'left',
        'prefixWidth': '80px'
      },
      'key': '1599801972000_90808'
    }, {
      'score': 0,
      'options': [{
        'score': 0,
        'id': '1599802216000_94173-1',
        'label': '无'
      }, {
        'score': 0,
        'children': [{
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': ' ',
            'prefixAlign': 'right',
            'suffixAlign': 'left',
            'width': '400px',
            'disabled': false,
            'inputType': 'textarea',
            'suffix': '',
            'prefixWidth': '20px',
            'suffixWidth': '40px'
          },
          'key': '1599802252000_9032'
        }],
        'id': '1599802216000_94173-2',
        'label': '有'
      }],
      'type': 'checkbox',
      'value': [],
      'config': {
        'prefixWeight': 'bold',
        'prefix': '术前用药：',
        'prefixAlign': 'left',
        'prefixWidth': '80px'
      },
      'key': '1599802216000_94173'
    }, {
      'columns': [{
        'padding': '0',
        'gapLR': '0',
        'children': [{
          'type': 'text',
          'value': '',
          'config': {
            'width': '170px',
            'weight': 'bold',
            'label': '跌倒/坠床危险性评估：',
            'align': 'left'
          },
          'key': '1600149589000_17179'
        }, {
          'type': 'button',
          'value': '',
          'config': {
            'assId': '10002',
            'scoreKey': '1599802471000_5976',
            'size': 'mini',
            'width': '80px',
            'label': '开始评估',
            'btnType': 'import',
            'importTitle': '跌倒/坠床危险性评估',
            'printHidden': true,
            'importTime': 'last'
          },
          'key': '1600149598000_36333'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefixWeight': 'bold',
            'borderLine': true,
            'readonly': false,
            'prefix': ' ',
            'prefixAlign': 'left',
            'suffixAlign': 'left',
            'width': '55px',
            'disabled': false,
            'inputType': 'text',
            'suffix': '分',
            'prefixWidth': '2px',
            'suffixWidth': '15px'
          },
          'key': '1599802471000_5976'
        }, {
          'score': 0,
          'options': [{
            'score': 0,
            'id': '1599802622000_75866-1',
            'label': '悬挂标示'
          }, {
            'score': 0,
            'id': '1599802622000_75866-2',
            'label': '加强巡视及看护'
          }, {
            'score': 0,
            'id': '1599802622000_75866-3',
            'label': '使用床栏'
          }, {
            'score': 0,
            'id': '1599802622000_75866-4',
            'label': '使用约束带'
          }],
          'type': 'checkbox',
          'value': [],
          'config': {
            'marginRight': '5px',
            'prefixWeight': 'bold',
            'prefix': '≥45分采取措施',
            'prefixAlign': 'right',
            'prefixWidth': '120px'
          },
          'key': '1599802622000_75866'
        }],
        'flex': 1,
        'justify': 'space-start',
        'width': '',
        'childWidth': 'auto',
        'align': 'center',
        'gapTB': '0',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0',
        'borderStyle': 'solid'
      },
      'key': '1599802419000_53809'
    }, {
      'columns': [{
        'padding': '0',
        'gapLR': '0',
        'children': [{
          'type': 'text',
          'value': '',
          'config': {
            'width': '170px',
            'weight': 'bold',
            'label': '压疮危险性评估：',
            'align': 'left'
          },
          'key': '1600148224000_83335'
        }, {
          'type': 'button',
          'value': '',
          'config': {
            'assId': '10004',
            'scoreKey': '1599803011000_76336',
            'size': 'mini',
            'width': '80px',
            'label': '开始评估',
            'btnType': 'import',
            'importTitle': '压疮危险性评估',
            'printHidden': true,
            'importTime': 'last'
          },
          'key': '1600148128000_25581'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefixWeight': 'bold',
            'borderLine': true,
            'readonly': false,
            'prefix': ' ',
            'prefixAlign': 'left',
            'suffixAlign': 'left',
            'width': '55px',
            'disabled': false,
            'inputType': 'text',
            'suffix': '分',
            'prefixWidth': '2px',
            'suffixWidth': '15px'
          },
          'key': '1599803011000_76336'
        }, {
          'score': 0,
          'options': [{
            'score': 0,
            'id': '1599803024000_88399-1',
            'label': '保持清洁干燥'
          }, {
            'score': 0,
            'id': '1599803024000_88399-2',
            'label': '及时翻身'
          }, {
            'score': 0,
            'id': '1599803024000_88399-3',
            'label': '局部减压'
          }, {
            'score': 0,
            'id': '1599803024000_88399-4',
            'label': '使用气垫床'
          }],
          'type': 'checkbox',
          'value': [],
          'config': {
            'marginRight': '5px',
            'prefixWeight': 'bold',
            'prefix': '≤18分采取措施',
            'prefixAlign': 'right',
            'prefixWidth': '120px'
          },
          'key': '1599803024000_88399'
        }],
        'flex': 1,
        'justify': 'space-start',
        'width': '',
        'childWidth': 'auto',
        'align': 'center',
        'gapTB': '0',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0',
        'borderStyle': 'solid'
      },
      'key': '1599803001000_29298'
    }, {
      'score': 0,
      'options': [{
        'score': 0,
        'id': '1599803161000_24096-1',
        'label': '正常'
      }, {
        'score': 0,
        'children': [{
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': ' ',
            'prefixAlign': 'right',
            'suffixAlign': 'left',
            'width': '400px',
            'disabled': false,
            'inputType': 'textarea',
            'suffix': '',
            'prefixWidth': '20px',
            'suffixWidth': '40px'
          },
          'key': '1599803175000_70594'
        }],
        'id': '1599803161000_24096-2',
        'label': '异常'
      }],
      'type': 'checkbox',
      'value': [],
      'config': {
        'prefixWeight': 'bold',
        'prefix': '皮肤状况：',
        'prefixAlign': 'left',
        'prefixWidth': '80px'
      },
      'key': '1599803161000_24096'
    }, {
      'columns': [{
        'padding': '0',
        'gapLR': '0',
        'children': [{
          'type': 'text',
          'value': '',
          'config': {
            'width': '90px',
            'weight': 'bold',
            'label': '自理能力：',
            'align': 'left'
          },
          'key': '1600151722000_39207'
        }, {
          'type': 'button',
          'value': '',
          'config': {
            'assId': '10007',
            'scoreKey': '1600151737000_78258',
            'size': 'mini',
            'width': '80px',
            'levelKey': '1600151743000_70185',
            'label': '开始评估',
            'btnType': 'import',
            'importTitle': '自理能力',
            'printHidden': true,
            'importTime': 'last'
          },
          'key': '1600151730000_50889'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': '分数',
            'prefixAlign': 'right',
            'suffixAlign': 'left',
            'width': '80px',
            'disabled': false,
            'inputType': 'text',
            'suffix': '',
            'prefixWidth': '50px',
            'suffixWidth': '40px'
          },
          'key': '1600151737000_78258'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': '风险评估',
            'prefixAlign': 'right',
            'suffixAlign': 'left',
            'width': '100px',
            'disabled': false,
            'inputType': 'text',
            'suffix': '',
            'prefixWidth': '70px',
            'suffixWidth': '40px'
          },
          'key': '1600151743000_70185'
        }],
        'flex': 1,
        'justify': 'space-start',
        'width': '',
        'childWidth': 'auto',
        'align': 'center',
        'gapTB': '0',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0',
        'borderStyle': 'solid'
      },
      'key': '1600151715000_49543'
    }, {
      'score': 0,
      'options': [{
        'score': 0,
        'id': '1599804656000_14754-1',
        'label': '1.指导床上大小便'
      }, {
        'score': 0,
        'id': '1599804656000_14754-2',
        'label': '2.指导功能锻炼、腹式呼吸、深呼吸及咳嗽咳痰'
      }, {
        'score': 0,
        'id': '1599804656000_14754-3',
        'label': '3.心理指导'
      }, {
        'score': 0,
        'id': '1599804656000_14754-4',
        'label': '4.术后常见的并发症'
      }, {
        'score': 0,
        'id': '1599804656000_14754-5',
        'label': '5.术前是否置管，置管名称及注意事项'
      }, {
        'score': 0,
        'id': '1599804656000_14754-6',
        'label': '6.肠道准备注意事项'
      }, {
        'score': 0,
        'id': '1599804656000_14754-7',
        'label': '7.手术体位'
      }, {
        'score': 0,
        'children': [],
        'id': '1599804656000_14754-8',
        'label': '8.禁饮食开始时间'
      }, {
        'score': 0,
        'id': '1599804656000_14754-9',
        'label': '9.咳痰护理'
      }, {
        'score': 0,
        'id': '1599804656000_14754-10',
        'label': '10.药物'
      }, {
        'checkboxHidden': true,
        'score': 0,
        'id': '1599804656000_14754-11',
        'label': '11.卫生处置：'
      }, {
        'score': 0,
        'id': '1599804656000_14754-12',
        'label': '洗澡'
      }, {
        'score': 0,
        'id': '1599804656000_14754-13',
        'label': '剪指（趾）甲'
      }, {
        'score': 0,
        'id': '1599804656000_14754-14',
        'label': '洗头'
      }, {
        'score': 0,
        'id': '1599804656000_14754-15',
        'label': '洗脚'
      }, {
        'score': 0,
        'id': '1599804656000_14754-16',
        'label': '更衣'
      }, {
        'checkboxHidden': true,
        'score': 0,
        'id': '1599804656000_14754-17',
        'label': '12.去手术室前的相关准备工作：'
      }, {
        'score': 0,
        'id': '1599804656000_14754-18',
        'label': '排空大小便'
      }, {
        'score': 0,
        'id': '1599804656000_14754-19',
        'label': '贴身穿病员服'
      }, {
        'score': 0,
        'id': '1599804656000_14754-20',
        'label': '取下义齿、首饰 、手表、眼镜及隐形眼镜'
      }, {
        'score': 0,
        'id': '1599804656000_14754-21',
        'label': '避免化妆、涂指甲油'
      }, {
        'score': 0,
        'id': '1599804656000_14754-22',
        'label': '术中带药'
      }, {
        'score': 0,
        'id': '1599804656000_14754-23',
        'label': 'CT片、MRI片'
      }, {
        'score': 0,
        'id': '1599804656000_14754-24',
        'label': '病历'
      }, {
        'score': 0,
        'id': '1599804656000_14754-25',
        'label': '13.手术时间'
      }, {
        'score': 0,
        'id': '1599804656000_14754-26',
        'label': '14.保证夜间睡眠'
      }, {
        'score': 0,
        'children': [{
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': ' ',
            'prefixAlign': 'right',
            'suffixAlign': 'left',
            'width': '400px',
            'disabled': false,
            'inputType': 'textarea',
            'suffix': '',
            'prefixWidth': '20px',
            'suffixWidth': '40px'
          },
          'key': '1599807333000_59780'
        }],
        'id': '1599804656000_14754-27',
        'label': '15.其他'
      }],
      'type': 'checkbox',
      'value': [],
      'config': {
        'prefixWeight': 'bold',
        'prefix': '术前宣教：',
        'prefixAlign': 'left',
        'prefixWidth': '80px'
      },
      'key': '1599804656000_14754'
    }, {
      'columns': [{
        'padding': '0',
        'gapLR': '0',
        'children': [{
          'score': 0,
          'options': [{
            'score': 0,
            'id': '1599808033000_51342-1',
            'label': '好'
          }, {
            'score': 0,
            'id': '1599808033000_51342-2',
            'label': '一般'
          }, {
            'score': 0,
            'id': '1599808033000_51342-3',
            'label': '差'
          }],
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefixWeight': 'bold',
            'prefix': '家庭支持：',
            'prefixAlign': 'left',
            'prefixWidth': '80px'
          },
          'key': '1599808033000_51342'
        }],
        'flex': '',
        'justify': 'space-start',
        'width': '420px',
        'childWidth': 'auto',
        'align': 'center',
        'gapTB': '0',
        'direction': 'row'
      }, {
        'padding': '0',
        'gapLR': '0',
        'children': [{
          'score': 0,
          'options': [{
            'score': 0,
            'id': '1599808264000_34689-1',
            'label': '良好'
          }, {
            'score': 0,
            'id': '1599808264000_34689-2',
            'label': '一般'
          }, {
            'score': 0,
            'id': '1599808264000_34689-3',
            'label': '差'
          }],
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefixWeight': 'bold',
            'prefix': '营养状况：',
            'prefixAlign': 'left',
            'prefixWidth': '100px'
          },
          'key': '1599808264000_34689'
        }],
        'flex': '',
        'justify': 'space-start',
        'width': '420px',
        'childWidth': 'auto',
        'align': 'center',
        'gapTB': '0',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0',
        'borderStyle': 'solid'
      },
      'key': '1599808572000_63176'
    }, {
      'columns': [{
        'padding': '0',
        'gapLR': '0',
        'children': [{
          'score': 0,
          'options': [{
            'score': 0,
            'id': '1599808457000_51133-1',
            'label': '良好'
          }, {
            'score': 0,
            'id': '1599808457000_51133-2',
            'label': '焦虑'
          }, {
            'score': 0,
            'id': '1599808457000_51133-3',
            'label': '抑郁'
          }, {
            'score': 0,
            'id': '1599808457000_51133-4',
            'label': '恐惧'
          }],
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefixWeight': 'bold',
            'prefix': '心理状态：',
            'prefixAlign': 'left',
            'prefixWidth': '80px'
          },
          'key': '1599808457000_51133'
        }],
        'flex': '',
        'justify': 'space-start',
        'width': '420px',
        'childWidth': 'auto',
        'align': 'center',
        'gapTB': '0',
        'direction': 'row'
      }, {
        'padding': '0',
        'gapLR': '0',
        'children': [{
          'score': 0,
          'options': [{
            'score': 0,
            'id': '1599808548000_47437-1',
            'label': '好'
          }, {
            'score': 0,
            'id': '1599808548000_47437-2',
            'label': '一般'
          }, {
            'score': 0,
            'id': '1599808548000_47437-3',
            'label': '差'
          }],
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefixWeight': 'bold',
            'prefix': '治疗依从性：',
            'prefixAlign': 'left',
            'prefixWidth': '100px'
          },
          'key': '1599808548000_47437'
        }],
        'flex': '',
        'justify': 'space-start',
        'width': '420px',
        'childWidth': 'auto',
        'align': 'center',
        'gapTB': '0',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0',
        'borderStyle': 'solid'
      },
      'key': '1599808180000_21106'
    }, {
      'columns': [{
        'padding': '0',
        'gapLR': '0',
        'children': [{
          'score': 0,
          'options': [{
            'score': 0,
            'id': '1599808834000_37242-1',
            'label': '好'
          }, {
            'score': 0,
            'id': '1599808834000_37242-2',
            'label': '一般'
          }, {
            'score': 0,
            'id': '1599808834000_37242-3',
            'label': '差'
          }],
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefixWeight': 'bold',
            'prefix': '家庭支持：',
            'prefixAlign': 'left',
            'prefixWidth': '80px'
          },
          'key': '1599808834000_37242'
        }],
        'flex': '',
        'justify': 'space-start',
        'width': '420px',
        'childWidth': 'auto',
        'align': 'center',
        'gapTB': '0',
        'direction': 'row'
      }, {
        'padding': '0',
        'gapLR': '0',
        'children': [{
          'score': 0,
          'options': [{
            'score': 0,
            'id': '1599808844000_21610-1',
            'label': '无'
          }, {
            'score': 0,
            'id': '1599808844000_21610-2',
            'label': '执行'
          }, {
            'score': 0,
            'id': '1599808844000_21610-3',
            'label': '未执行'
          }],
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefixWeight': 'bold',
            'prefix': '手术用物准备：',
            'prefixAlign': 'left',
            'prefixWidth': '120px'
          },
          'key': '1599808844000_21610'
        }],
        'flex': '',
        'justify': 'space-start',
        'width': '420px',
        'childWidth': 'auto',
        'align': 'center',
        'gapTB': '0',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0',
        'borderStyle': 'solid'
      },
      'key': '1599808826000_39747'
    }, {
      'columns': [{
        'padding': '0',
        'gapLR': '0',
        'children': [{
          'type': 'text',
          'value': '',
          'config': {
            'width': '90px',
            'weight': 'bold',
            'label': '疼痛分级：',
            'align': 'left'
          },
          'key': '1600150844000_85026'
        }, {
          'type': 'button',
          'value': '',
          'config': {
            'assId': '10009',
            'showEdit': true,
            'scoreKey': '1600151315000_89072',
            'size': 'mini',
            'width': '80px',
            'levelKey': '1600151328000_31307',
            'label': '开始评估',
            'btnType': 'import',
            'importTitle': '疼痛分级',
            'printHidden': true,
            'importTime': 'last'
          },
          'key': '1600151133000_77742'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': '分数',
            'prefixAlign': 'right',
            'suffixAlign': 'left',
            'width': '80px',
            'disabled': false,
            'inputType': 'text',
            'suffix': '',
            'prefixWidth': '50px',
            'suffixWidth': '40px'
          },
          'key': '1600151315000_89072'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': '风险评估',
            'prefixAlign': 'right',
            'suffixAlign': 'left',
            'width': '100px',
            'disabled': false,
            'inputType': 'text',
            'suffix': '',
            'prefixWidth': '70px',
            'suffixWidth': '40px'
          },
          'key': '1600151328000_31307'
        }],
        'flex': 1,
        'justify': 'space-start',
        'width': '',
        'childWidth': 'auto',
        'align': 'center',
        'gapTB': '0',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0',
        'borderStyle': 'solid'
      },
      'key': '1600150851000_45974'
    }, {
      'score': 0,
      'options': [{
        'score': 0,
        'id': '1599809017000_46302-1',
        'label': '心理护理'
      }, {
        'score': 0,
        'id': '1599809017000_46302-2',
        'label': '通知医生'
      }, {
        'score': 0,
        'children': [{
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': ' ',
            'prefixAlign': 'right',
            'suffixAlign': 'left',
            'width': '200px',
            'disabled': false,
            'inputType': 'textarea',
            'suffix': '',
            'prefixWidth': '20px',
            'suffixWidth': '40px'
          },
          'key': '1599809190000_40918'
        }],
        'id': '1599809017000_46302-3',
        'label': '用药'
      }],
      'type': 'checkbox',
      'value': [],
      'config': {
        'marginRight': '10px',
        'prefixWeight': 'bold',
        'prefix': '疼痛症状管理：',
        'prefixAlign': 'left',
        'prefixWidth': '120px'
      },
      'key': '1599809017000_46302'
    }, {
      'score': 0,
      'type': 'input',
      'value': '',
      'config': {
        'prefixWeight': 'bold',
        'borderLine': true,
        'readonly': false,
        'prefix': '其他:',
        'prefixAlign': 'left',
        'suffixAlign': 'left',
        'width': '400px',
        'disabled': false,
        'inputType': 'textarea',
        'suffix': '',
        'prefixWidth': '70px',
        'suffixWidth': '40px'
      },
      'key': '1599811065000_41425'
    }, {
      'columns': [{
        'padding': '',
        'gapLR': '',
        'flex': '',
        'justify': 'flex-start',
        'width': '300px',
        'childWidth': 'auto',
        'align': 'flex-start',
        'gapTB': '5px',
        'direction': 'column'
      }, {
        'padding': '',
        'gapLR': '',
        'children': [{
          'type': 'button',
          'value': '',
          'config': {
            'size': 'mini',
            'width': '80px',
            'signTimeKey': '1600137626000_52105',
            'signKey': '1600137616000_54170',
            'label': '签名',
            'btnType': 'signature',
            'printHidden': true
          },
          'key': '1600137607000_91349'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefixWeight': 'bold',
            'borderLine': true,
            'readonly': false,
            'prefix': '护士签名：',
            'prefixAlign': 'right',
            'suffixAlign': 'left',
            'width': '100px',
            'disabled': false,
            'inputType': 'text',
            'suffix': '',
            'prefixWidth': '100px',
            'suffixWidth': '20px'
          },
          'key': '1600137616000_54170'
        }, {
          'score': 0,
          'type': 'date',
          'value': '',
          'config': {
            'readonly': false,
            'prefix': '时间：',
            'prefixAlign': 'right',
            'width': '190px',
            'disabled': false,
            'placeholder': '',
            'type': 'datetime',
            'prefixWidth': '50px'
          },
          'key': '1600137626000_52105'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '',
        'childWidth': 'auto',
        'align': 'flex-start',
        'gapTB': '5px',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0px',
        'borderStyle': 'solid'
      },
      'key': '1599811344000_39906'
    }],
    'flex': 1,
    'justify': 'flex-start',
    'width': '',
    'childWidth': 'auto',
    'align': 'flex-start',
    'gapTB': '5px',
    'direction': 'column'
  }],
  'type': 'grid',
  'value': '',
  'config': {
    'borderColor': '#ddd',
    'borderWidth': '1px',
    'borderStyle': 'solid'
  },
  'key': '1599793548000_73536'
}, {
  'columns': [{
    'padding': '10px',
    'gapLR': '',
    'children': [{
      'columns': [{
        'padding': '',
        'gapLR': '',
        'children': [{
          'score': 0,
          'options': [{
            'score': 0,
            'id': '1599812383000_82189-1',
            'label': '好'
          }, {
            'score': 0,
            'id': '1599812383000_82189-2',
            'label': '一般'
          }, {
            'score': 0,
            'id': '1599812383000_82189-3',
            'label': '差'
          }],
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefixWeight': 'bold',
            'prefix': '睡眠情况：',
            'prefixAlign': 'left',
            'prefixWidth': '80px'
          },
          'key': '1599812383000_82189'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': '用药：',
            'prefixAlign': 'right',
            'suffixAlign': 'left',
            'width': '150px',
            'disabled': false,
            'inputType': 'textarea',
            'suffix': '',
            'prefixWidth': '60px',
            'suffixWidth': '20px'
          },
          'key': '1599812544000_88493'
        }, {
          'score': 0,
          'type': 'date',
          'value': '',
          'config': {
            'readonly': false,
            'prefix': '时间',
            'prefixAlign': 'right',
            'width': '190px',
            'disabled': false,
            'placeholder': '',
            'type': 'datetime',
            'prefixWidth': '100px'
          },
          'key': '1599812745000_13079'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '',
        'childWidth': 'auto',
        'align': 'center',
        'gapTB': '0',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0',
        'borderStyle': 'solid'
      },
      'key': '1599812083000_19049'
    }, {
      'columns': [{
        'padding': '',
        'gapLR': '',
        'children': [{
          'score': 0,
          'type': 'date',
          'value': '',
          'config': {
            'prefixWeight': 'bold',
            'readonly': false,
            'prefix': '禁饮食开始时间：',
            'prefixAlign': 'left',
            'width': '190px',
            'disabled': false,
            'placeholder': '',
            'type': 'datetime',
            'prefixWidth': '130px'
          },
          'key': '1599812965000_55268'
        }, {
          'score': 0,
          'options': [{
            'score': 0,
            'id': '1599812987000_38818-1',
            'label': '已告知'
          }, {
            'score': 0,
            'id': '1599812987000_38818-2',
            'label': '未告知'
          }],
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefixWeight': 'bold',
            'prefix': ' ',
            'prefixAlign': 'left',
            'prefixWidth': '20px'
          },
          'key': '1599812987000_38818'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '',
        'childWidth': 'auto',
        'align': 'center',
        'gapTB': '0',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0',
        'borderStyle': 'solid'
      },
      'key': '1599812878000_19383'
    }, {
      'columns': [{
        'padding': '',
        'gapLR': '',
        'children': [{
          'score': 0,
          'options': [{
            'score': 0,
            'id': '1599813314000_74415-1',
            'label': '已告知'
          }, {
            'score': 0,
            'id': '1599813314000_74415-2',
            'label': '未告知'
          }],
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefixWeight': 'bold',
            'prefix': '去手术室前的相关准备工作：',
            'prefixAlign': 'left',
            'prefixWidth': '220px'
          },
          'key': '1599813314000_74415'
        }, {
          'score': 0,
          'options': [{
            'score': 0,
            'id': '1599813392000_8118-1',
            'label': '已执行'
          }, {
            'score': 0,
            'id': '1599813392000_8118-2',
            'label': '未执行'
          }],
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefixWeight': 'bold',
            'prefix': '卫生处置：',
            'prefixAlign': 'right',
            'prefixWidth': '150px'
          },
          'key': '1599813392000_8118'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '',
        'childWidth': 'auto',
        'align': 'center',
        'gapTB': '0',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0',
        'borderStyle': 'solid'
      },
      'key': '1599813277000_77180'
    }, {
      'score': 0,
      'type': 'input',
      'value': '',
      'config': {
        'prefixWeight': 'bold',
        'borderLine': true,
        'readonly': false,
        'prefix': '其他:',
        'prefixAlign': 'left',
        'suffixAlign': 'left',
        'width': '400px',
        'disabled': false,
        'inputType': 'textarea',
        'suffix': '',
        'prefixWidth': '70px',
        'suffixWidth': '40px'
      },
      'key': '1599813723000_7065'
    }, {
      'columns': [{
        'padding': '',
        'gapLR': '',
        'flex': '',
        'justify': 'flex-start',
        'width': '300px',
        'childWidth': 'auto',
        'align': 'flex-start',
        'gapTB': '5px',
        'direction': 'column'
      }, {
        'padding': '',
        'gapLR': '',
        'children': [{
          'type': 'button',
          'value': '',
          'config': {
            'size': 'mini',
            'width': '80px',
            'signTimeKey': '1600137729000_35198',
            'signKey': '1600137720000_80442',
            'label': '签名',
            'btnType': 'signature',
            'printHidden': true
          },
          'key': '1600137710000_73330'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefixWeight': 'bold',
            'borderLine': true,
            'readonly': false,
            'prefix': '护士签名：',
            'prefixAlign': 'right',
            'suffixAlign': 'left',
            'width': '100px',
            'disabled': false,
            'inputType': 'text',
            'suffix': '',
            'prefixWidth': '100px',
            'suffixWidth': '20px'
          },
          'key': '1600137720000_80442'
        }, {
          'score': 0,
          'type': 'date',
          'value': '',
          'config': {
            'readonly': false,
            'prefix': '时间：',
            'prefixAlign': 'right',
            'width': '190px',
            'disabled': false,
            'placeholder': '',
            'type': 'datetime',
            'prefixWidth': '50px'
          },
          'key': '1600137729000_35198'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '',
        'childWidth': 'auto',
        'align': 'flex-start',
        'gapTB': '5px',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0px',
        'borderStyle': 'solid'
      },
      'key': '1599813731000_38645'
    }],
    'flex': 1,
    'justify': 'flex-start',
    'width': '',
    'childWidth': 'auto',
    'align': 'flex-start',
    'gapTB': '5px',
    'direction': 'column'
  }],
  'type': 'grid',
  'value': '',
  'config': {
    'borderColor': '#ddd',
    'borderWidth': '1px',
    'borderStyle': 'solid'
  },
  'key': '1599812083000_19049'
}, {
  'columns': [{
    'padding': '10px',
    'gapLR': '',
    'children': [{
      'columns': [{
        'padding': '0',
        'gapLR': '0',
        'children': [{
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefixWeight': 'bold',
            'borderLine': true,
            'readonly': false,
            'prefix': 'T',
            'prefixAlign': 'left',
            'suffixAlign': 'left',
            'width': '70px',
            'disabled': false,
            'inputType': 'text',
            'suffix': '℃',
            'prefixWidth': '10px',
            'suffixWidth': '20px'
          },
          'key': '1599814300000_59121'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefixWeight': 'bold',
            'borderLine': true,
            'readonly': false,
            'prefix': 'P',
            'prefixAlign': 'right',
            'suffixAlign': 'left',
            'width': '70px',
            'disabled': false,
            'inputType': 'text',
            'suffix': '次/分',
            'prefixWidth': '20px',
            'suffixWidth': '40px'
          },
          'key': '1599814309000_54991'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefixWeight': 'bold',
            'borderLine': true,
            'readonly': false,
            'prefix': 'R',
            'prefixAlign': 'right',
            'suffixAlign': 'left',
            'width': '70px',
            'disabled': false,
            'inputType': 'text',
            'suffix': '次/分',
            'prefixWidth': '20px',
            'suffixWidth': '40px'
          },
          'key': '1599814319000_17674'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefixWeight': 'bold',
            'borderLine': true,
            'readonly': false,
            'prefix': 'BP',
            'prefixAlign': 'right',
            'suffixAlign': 'left',
            'width': '70px',
            'disabled': false,
            'inputType': 'text',
            'suffix': 'mmHg',
            'prefixWidth': '20px',
            'suffixWidth': '60px'
          },
          'key': '1599814325000_65921'
        }, {
          'score': 0,
          'type': 'date',
          'value': '',
          'config': {
            'readonly': false,
            'prefix': '测量时间',
            'prefixAlign': 'right',
            'width': '190px',
            'disabled': false,
            'placeholder': '',
            'type': 'datetime',
            'prefixWidth': '70px'
          },
          'key': '1599814332000_25111'
        }],
        'flex': 1,
        'justify': 'space-between',
        'width': '',
        'childWidth': 'auto',
        'align': 'center',
        'gapTB': '0',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0',
        'borderStyle': 'solid'
      },
      'key': '1599814292000_82765'
    }, {
      'columns': [{
        'padding': '',
        'gapLR': '',
        'children': [{
          'score': 0,
          'options': [{
            'score': 0,
            'id': '1599813973000_67739-1',
            'label': '好'
          }, {
            'score': 0,
            'id': '1599813973000_67739-2',
            'label': '一般'
          }, {
            'score': 0,
            'id': '1599813973000_67739-3',
            'label': '差'
          }],
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefixWeight': 'bold',
            'prefix': '睡眠情况：',
            'prefixAlign': 'left',
            'prefixWidth': '80px'
          },
          'key': '1599813973000_67739'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': '用药：',
            'prefixAlign': 'right',
            'suffixAlign': 'left',
            'width': '150px',
            'disabled': false,
            'inputType': 'textarea',
            'suffix': '',
            'prefixWidth': '60px',
            'suffixWidth': '20px'
          },
          'key': '1599813999000_36839'
        }, {
          'score': 0,
          'type': 'date',
          'value': '',
          'config': {
            'readonly': false,
            'prefix': '时间',
            'prefixAlign': 'right',
            'width': '190px',
            'disabled': false,
            'placeholder': '',
            'type': 'datetime',
            'prefixWidth': '100px'
          },
          'key': '1599814006000_40053'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '',
        'childWidth': 'auto',
        'align': 'center',
        'gapTB': '0',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0',
        'borderStyle': 'solid'
      },
      'key': '1599813962000_59999'
    }, {
      'columns': [{
        'padding': '',
        'gapLR': '',
        'children': [{
          'score': 0,
          'type': 'date',
          'value': '',
          'config': {
            'prefixWeight': 'bold',
            'readonly': false,
            'prefix': '禁饮食开始时间：',
            'prefixAlign': 'left',
            'width': '190px',
            'disabled': false,
            'placeholder': '',
            'type': 'datetime',
            'prefixWidth': '130px'
          },
          'key': '1599814044000_68574'
        }, {
          'score': 0,
          'options': [{
            'score': 0,
            'id': '1599814054000_31493-1',
            'label': '已告知'
          }, {
            'score': 0,
            'id': '1599814054000_31493-2',
            'label': '未告知'
          }],
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefixWeight': 'bold',
            'prefix': ' ',
            'prefixAlign': 'left',
            'prefixWidth': '20px'
          },
          'key': '1599814054000_31493'
        }, {
          'score': 0,
          'options': [{
            'score': 0,
            'id': '1599814105000_44201-1',
            'label': '已执行'
          }, {
            'score': 0,
            'id': '1599814105000_44201-2',
            'label': '未执行'
          }],
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefixWeight': 'bold',
            'prefix': '卫生处置：',
            'prefixAlign': 'right',
            'prefixWidth': '150px'
          },
          'key': '1599814105000_44201'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '',
        'childWidth': 'auto',
        'align': 'center',
        'gapTB': '0',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0',
        'borderStyle': 'solid'
      },
      'key': '1599814021000_59778'
    }, {
      'score': 0,
      'options': [{
        'score': 0,
        'id': '1599815219000_9134-1',
        'label': '无'
      }, {
        'score': 0,
        'children': [{
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefixWeight': 'bold',
            'borderLine': true,
            'readonly': false,
            'prefix': '',
            'prefixAlign': 'left',
            'suffixAlign': 'left',
            'width': '200px',
            'disabled': false,
            'inputType': 'textarea',
            'suffix': '',
            'prefixWidth': '70px',
            'suffixWidth': '40px'
          },
          'key': '1599815310000_3658'
        }, {
          'score': 0,
          'options': [{
            'score': 0,
            'children': [{
              'score': 0,
              'type': 'date',
              'value': '',
              'config': {
                'readonly': false,
                'prefix': '执行时间',
                'prefixAlign': 'right',
                'width': '190px',
                'disabled': false,
                'placeholder': '',
                'type': 'datetime',
                'prefixWidth': '70px'
              },
              'key': '1599815498000_55177'
            }],
            'id': '1599815395000_45690-1',
            'label': '已执行'
          }, {
            'score': 0,
            'id': '1599815395000_45690-2',
            'label': '未执行'
          }],
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefixWeight': 'bold',
            'prefix': '',
            'prefixAlign': 'left',
            'prefixWidth': '70px'
          },
          'key': '1599815395000_45690'
        }],
        'id': '1599815219000_9134-2',
        'label': '有'
      }],
      'type': 'checkbox',
      'value': [],
      'config': {
        'prefixWeight': 'bold',
        'prefix': '术前用药：',
        'prefixAlign': 'left',
        'prefixWidth': '80px'
      },
      'key': '1599815219000_9134'
    }, {
      'columns': [{
        'padding': '',
        'gapLR': '',
        'children': [{
          'score': 0,
          'options': [{
            'score': 0,
            'id': '1599814087000_22035-1',
            'label': '已执行'
          }, {
            'score': 0,
            'id': '1599814087000_22035-2',
            'label': '未执行'
          }],
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefixWeight': 'bold',
            'prefix': '去手术室前的相关准备工作：',
            'prefixAlign': 'left',
            'prefixWidth': '220px'
          },
          'key': '1599814087000_22035'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '',
        'childWidth': 'auto',
        'align': 'center',
        'gapTB': '0',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0',
        'borderStyle': 'solid'
      },
      'key': '1599814073000_6578'
    }, {
      'score': 0,
      'options': [{
        'score': 0,
        'children': [{
          'score': 0,
          'type': 'date',
          'value': '',
          'config': {
            'readonly': false,
            'prefix': '时间',
            'prefixAlign': 'right',
            'width': '190px',
            'disabled': false,
            'placeholder': '',
            'type': 'datetime',
            'prefixWidth': '40px'
          },
          'key': '1599815605000_83913'
        }],
        'id': '1599815572000_3761-1',
        'label': '已去'
      }, {
        'score': 0,
        'id': '1599815572000_3761-2',
        'label': '未去'
      }],
      'type': 'checkbox',
      'value': [],
      'config': {
        'prefixWeight': 'bold',
        'prefix': '去手术室时间：',
        'prefixAlign': 'left',
        'prefixWidth': '120px'
      },
      'key': '1599815572000_3761'
    }, {
      'score': 0,
      'type': 'input',
      'value': '',
      'config': {
        'prefixWeight': 'bold',
        'borderLine': true,
        'readonly': false,
        'prefix': '其他:',
        'prefixAlign': 'left',
        'suffixAlign': 'left',
        'width': '400px',
        'disabled': false,
        'inputType': 'textarea',
        'suffix': '',
        'prefixWidth': '70px',
        'suffixWidth': '40px'
      },
      'key': '1599814123000_10531'
    }, {
      'columns': [{
        'padding': '',
        'gapLR': '',
        'flex': '',
        'justify': 'flex-start',
        'width': '300px',
        'childWidth': 'auto',
        'align': 'flex-start',
        'gapTB': '5px',
        'direction': 'column'
      }, {
        'padding': '',
        'gapLR': '',
        'children': [{
          'type': 'button',
          'value': '',
          'config': {
            'size': 'mini',
            'width': '80px',
            'signTimeKey': '1600137774000_59420',
            'signKey': '1600137764000_83834',
            'label': '签名',
            'btnType': 'signature',
            'printHidden': true
          },
          'key': '1600137757000_30084'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefixWeight': 'bold',
            'borderLine': true,
            'readonly': false,
            'prefix': '护士签名：',
            'prefixAlign': 'right',
            'suffixAlign': 'left',
            'width': '100px',
            'disabled': false,
            'inputType': 'text',
            'suffix': '',
            'prefixWidth': '100px',
            'suffixWidth': '20px'
          },
          'key': '1600137764000_83834'
        }, {
          'score': 0,
          'type': 'date',
          'value': '',
          'config': {
            'readonly': false,
            'prefix': '时间：',
            'prefixAlign': 'right',
            'width': '190px',
            'disabled': false,
            'placeholder': '',
            'type': 'datetime',
            'prefixWidth': '50px'
          },
          'key': '1600137774000_59420'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '',
        'childWidth': 'auto',
        'align': 'flex-start',
        'gapTB': '5px',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0px',
        'borderStyle': 'solid'
      },
      'key': '1599814149000_71728'
    }],
    'flex': 1,
    'justify': 'flex-start',
    'width': '',
    'childWidth': 'auto',
    'align': 'flex-start',
    'gapTB': '5px',
    'direction': 'column'
  }],
  'type': 'grid',
  'value': '',
  'config': {
    'borderColor': '#ddd',
    'borderWidth': '1px',
    'borderStyle': 'solid'
  },
  'key': '1599813953000_59808'
}]
