// 中心医院入院评估
export const zhongxinRuyuanAssess =
    [{
      'columns': [{
        'padding': '0 0 0 5px',
        'gapLR': '0',
        'children': [{
          'score': 0,
          'mConfig': {},
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': '初步诊断:',
            'prefixAlign': 'left',
            'width': '400px',
            'disabled': false,
            'inputType': 'text',
            'prefixWidth': '70px'
          },
          'key': '1617169577000_42874'
        }, {
          'score': 0,
          'mConfig': {},
          'type': 'date',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': '入院时间:',
            'prefixAlign': 'left',
            'width': '170px',
            'disabled': false,
            'type': 'date',
            'prefixWidth': '70px',
            'noCenter': true
          },
          'key': '1617169577000_17551'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '100%',
        'childWidth': '',
        'align': 'center',
        'gapTB': '2px',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0',
        'borderStyle': 'solid'
      },
      'key': '1617169577000_20364'
    }, {
      'columns': [{
        'padding': '0 0 0 5px',
        'gapLR': '0',
        'children': [{
          'options': [{
            'score': 0,
            'id': '1617169577000_45412-0',
            'label': '急诊'
          }, {
            'score': 0,
            'id': '1617169577000_45412-1',
            'label': '门诊'
          }, {
            'score': 0,
            'id': '1617169577000_45412-2',
            'label': '转诊'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '入院方式：',
            'prefixWidth': '80px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_45412'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '100%',
        'childWidth': '',
        'align': 'center',
        'gapTB': '2px',
        'direction': 'row'
      }, {
        'padding': '0 0 0 5px',
        'gapLR': '0',
        'children': [{
          'options': [{
            'score': 0,
            'id': '1617169577000_48711-0',
            'label': '步行',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_48711-1',
            'label': '轮椅',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_48711-2',
            'label': '平车',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_48711-3',
            'label': '其他',
            'marginRight': '0px'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '入院方式：',
            'prefixWidth': '80px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_48711'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '100%',
        'childWidth': '',
        'align': 'center',
        'gapTB': '2px',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0px',
        'borderStyle': 'solid'
      },
      'key': '1617169577000_12591'
    }, {
      'columns': [{
        'padding': '0 0 0 5px',
        'gapLR': '0',
        'children': [{
          'options': [{
            'score': 0,
            'id': '1617169577000_47957-0',
            'label': '患者'
          }, {
            'score': 0,
            'id': '1617169577000_47957-1',
            'label': '家属'
          }, {
            'score': 0,
            'id': '1617169577000_47957-2',
            'label': '知情者'
          }, {
            'score': 0,
            'id': '1617169577000_47957-3',
            'label': '各种资料'
          }, {
            'score': 0,
            'id': '1617169577000_47957-4',
            'label': '护理体检'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '资料来源：',
            'prefixWidth': '80px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_47957'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '100%',
        'childWidth': '',
        'align': 'center',
        'gapTB': '2px',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0px',
        'borderStyle': 'solid'
      },
      'key': '1617169577000_11065'
    }, {
      'columns': [{
        'padding': '0 0 0 5px',
        'gapLR': '0',
        'children': [{
          'columns': [{
            'padding': '',
            'gapLR': '0',
            'children': [{
              'options': [{
                'score': 0,
                'id': '1617169577000_79913-0',
                'label': '无'
              }, {
                'score': 0,
                'id': '1617169577000_79913-1',
                'label': '已戒烟'
              }, {
                'score': 0,
                'id': '1617169577000_79913-2',
                'label': '有',
                'children': [{
                  'score': 0,
                  'mConfig': {},
                  'type': 'input',
                  'value': '',
                  'config': {
                    'borderLine': true,
                    'readonly': false,
                    'prefix': '',
                    'prefixAlign': 'left',
                    'width': '50px',
                    'disabled': true,
                    'inputType': 'input',
                    'prefixWidth': '60px',
                    'suffix': '包/日',
                    'keyDisabled': '1617169577000_79913-2'
                  },
                  'key': '1617169577000_32947'
                }, {
                  'score': 0,
                  'mConfig': {},
                  'type': 'input',
                  'value': '',
                  'config': {
                    'borderLine': true,
                    'readonly': false,
                    'prefix': '已吸',
                    'prefixAlign': 'left',
                    'width': '50px',
                    'disabled': true,
                    'inputType': 'input',
                    'prefixWidth': '30px',
                    'suffix': '年',
                    'keyDisabled': '1617169577000_79913-2'
                  },
                  'key': '1617169577000_55444'
                }, {
                  'score': 0,
                  'mConfig': {},
                  'type': 'input',
                  'value': '',
                  'config': {
                    'borderLine': true,
                    'readonly': false,
                    'prefix': '停止吸烟',
                    'prefixAlign': 'left',
                    'width': '50px',
                    'disabled': true,
                    'inputType': 'input',
                    'prefixWidth': '60px',
                    'suffix': '天',
                    'keyDisabled': '1617169577000_79913-2'
                  },
                  'key': '1617169577000_70700'
                }]
              }],
              'score': 0,
              'type': 'checkbox',
              'value': [],
              'config': {
                'prefix': '生活习惯：吸烟：',
                'prefixWidth': '130px',
                'borderLine': true,
                'readonly': false,
                'disabled': false,
                'inputType': 'checkbox',
                'isRadio': true
              },
              'key': '1617169577000_79913'
            }, {
              'options': [{
                'score': 0,
                'id': '1617169577000_11446-0',
                'label': '无',
                'marginLeft': '19px'
              }, {
                'score': 0,
                'id': '1617169577000_11446-1',
                'label': '已戒酒'
              }, {
                'score': 0,
                'id': '1617169577000_11446-2',
                'label': '有',
                'children': [{
                  'score': 0,
                  'mConfig': {},
                  'type': 'input',
                  'value': '',
                  'config': {
                    'borderLine': true,
                    'readonly': false,
                    'prefix': '',
                    'prefixAlign': 'left',
                    'width': '50px',
                    'disabled': true,
                    'inputType': 'input',
                    'prefixWidth': '60px',
                    'suffix': 'ml/日',
                    'keyDisabled': '1617169577000_11446-2'
                  },
                  'key': '1617169577000_62470'
                }, {
                  'score': 0,
                  'mConfig': {},
                  'type': 'input',
                  'value': '',
                  'config': {
                    'borderLine': true,
                    'readonly': false,
                    'prefix': '已饮',
                    'prefixAlign': 'left',
                    'width': '50px',
                    'disabled': true,
                    'inputType': 'input',
                    'prefixWidth': '30px',
                    'suffix': '年',
                    'keyDisabled': '1617169577000_11446-2'
                  },
                  'key': '1617169577000_89045'
                }]
              }, {
                'score': 0,
                'id': '1617169577000_11446-3',
                'label': '偶尔'
              }],
              'score': 0,
              'type': 'checkbox',
              'value': [],
              'config': {
                'prefix': '饮酒：',
                'prefixWidth': '112px',
                'borderLine': true,
                'readonly': false,
                'disabled': false,
                'inputType': 'checkbox',
                'prefixAlign': 'right',
                'isRadio': true
              },
              'key': '1617169577000_11446'
            }],
            'flex': 1,
            'justify': 'flex-start',
            'width': '',
            'childWidth': '',
            'align': 'center',
            'gapTB': '',
            'direction': 'row'
          }],
          'type': 'grid',
          'value': '',
          'config': {
            'borderColor': '#ddd',
            'borderWidth': '0px',
            'borderStyle': 'solid'
          },
          'key': '1617169577000_89966'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '100%',
        'childWidth': '',
        'align': 'center',
        'gapTB': '2px',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0px',
        'borderStyle': 'solid'
      },
      'key': '1617169577000_11438'
    }, {
      'columns': [{
        'padding': '0 0 0 5px',
        'gapLR': '0',
        'children': [{
          'options': [{
            'score': 0,
            'id': '1617169577000_34728-0',
            'label': '无'
          }, {
            'score': 0,
            'id': '1617169577000_34728-1',
            'label': '有',
            'children': [{
              'options': [{
                'score': 0,
                'id': '1617169577000_42970-0',
                'label': '高血压'
              }, {
                'score': 0,
                'id': '1617169577000_42970-1',
                'label': '冠心病'
              }, {
                'score': 0,
                'id': '1617169577000_42970-2',
                'label': '糖尿病',
                'marginRight': '10px'
              }],
              'score': 0,
              'type': 'checkbox',
              'value': [],
              'config': {
                'prefix': '',
                'prefixWidth': '60px',
                'borderLine': true,
                'readonly': false,
                'disabled': true,
                'inputType': 'checkbox',
                'keyDisabled': '1617169577000_34728-1'
              },
              'key': '1617169577000_42970'
            }]
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '既往史（含手术史）：',
            'prefixWidth': '150px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_34728'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefix': '其他',
            'prefixWidth': '40px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'input',
            'width': '150px'
          },
          'key': '1617169577000_98531'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '100%',
        'childWidth': '',
        'align': 'center',
        'gapTB': '2px',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0px',
        'borderStyle': 'solid'
      },
      'key': '1617169577000_24015'
    }, {
      'columns': [{
        'padding': '0 0 0 5px',
        'gapLR': '0',
        'children': [{
          'options': [{
            'score': 0,
            'id': '1617169577000_43413-0',
            'label': '无'
          }, {
            'score': 0,
            'id': '1617169577000_43413-1',
            'label': '有',
            'children': [{
              'score': 0,
              'type': 'input',
              'value': '',
              'config': {
                'prefix': '食物',
                'prefixWidth': '30px',
                'borderLine': true,
                'readonly': false,
                'disabled': true,
                'inputType': 'input',
                'width': '100px',
                'keyDisabled': '1617169577000_43413-1'
              },
              'key': '1617169577000_73418'
            }, {
              'score': 0,
              'type': 'input',
              'value': '',
              'config': {
                'prefix': '药物',
                'prefixWidth': '30px',
                'borderLine': true,
                'readonly': false,
                'disabled': true,
                'inputType': 'input',
                'width': '100px',
                'keyDisabled': '1617169577000_43413-1'
              },
              'key': '1617169577000_1340'
            }, {
              'score': 0,
              'type': 'input',
              'value': '',
              'config': {
                'prefix': '输血',
                'prefixWidth': '30px',
                'borderLine': true,
                'readonly': false,
                'disabled': true,
                'inputType': 'input',
                'width': '100px',
                'keyDisabled': '1617169577000_43413-1'
              },
              'key': '1617169577000_67258'
            }]
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '过敏史：',
            'prefixWidth': '80px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_43413'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefix': '其他',
            'prefixWidth': '50px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'input',
            'width': '150px',
            'prefixAlign': 'right'
          },
          'key': '1617169577000_36256'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '100%',
        'childWidth': '',
        'align': 'center',
        'gapTB': '2px',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0px',
        'borderStyle': 'solid'
      },
      'key': '1617169577000_4089'
    }, {
      'columns': [{
        'padding': '0 0 0 5px',
        'gapLR': '0',
        'children': [{
          'options': [{
            'score': 0,
            'id': '1617169577000_95421-0',
            'label': '无'
          }, {
            'score': 0,
            'id': '1617169577000_95421-1',
            'label': '有',
            'children': [{
              'score': 0,
              'type': 'input',
              'value': '',
              'config': {
                'prefix': '',
                'prefixWidth': '',
                'borderLine': true,
                'readonly': false,
                'disabled': true,
                'inputType': 'input',
                'width': '200px',
                'keyDisabled': '1617169577000_95421-1'
              },
              'key': '1617169577000_86831'
            }]
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '传染病史：',
            'prefixWidth': '80px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_95421'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_71897-0',
            'label': '无'
          }, {
            'score': 0,
            'id': '1617169577000_71897-1',
            'label': '有',
            'children': [{
              'score': 0,
              'type': 'input',
              'value': '',
              'config': {
                'prefix': '',
                'prefixWidth': '',
                'borderLine': true,
                'readonly': false,
                'disabled': true,
                'inputType': 'input',
                'width': '200px',
                'keyDisabled': '1617169577000_71897-1'
              },
              'key': '1617169577000_17682'
            }]
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '家族史：',
            'prefixWidth': '70px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_71897'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '100%',
        'childWidth': '',
        'align': 'center',
        'gapTB': '2px',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0px',
        'borderStyle': 'solid'
      },
      'key': '1617169577000_34545'
    }, {
      'columns': [{
        'padding': '0 0 0 5px',
        'gapLR': '0',
        'children': [{
          'score': 0,
          'mConfig': {},
          'type': 'text',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'label': '社会评估:',
            'align': 'left',
            'width': '900px',
            'disabled': false,
            'inputType': 'text'
          },
          'key': '1617169577000_76295'
        }, {
          'score': 0,
          'mConfig': {},
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': '国籍:',
            'prefixAlign': 'left',
            'width': '100px',
            'disabled': false,
            'inputType': 'text',
            'prefixWidth': '40px'
          },
          'key': '1617169577000_11545'
        }, {
          'score': 0,
          'mConfig': {},
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': '其他:',
            'prefixAlign': 'left',
            'width': '100px',
            'disabled': false,
            'inputType': 'text',
            'prefixWidth': '40px'
          },
          'key': '1617169577000_69785'
        }, {
          'score': 0,
          'mConfig': {},
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': '籍贯:',
            'prefixAlign': 'left',
            'width': '100px',
            'disabled': false,
            'inputType': 'text',
            'prefixWidth': '40px'
          },
          'key': '1617169577000_39678'
        }, {
          'score': 0,
          'mConfig': {},
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': '民族:',
            'prefixAlign': 'left',
            'width': '70px',
            'disabled': false,
            'inputType': 'text',
            'prefixWidth': '40px'
          },
          'key': '1617169577000_16692'
        }, {
          'score': 0,
          'mConfig': {},
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': '职业:',
            'prefixAlign': 'left',
            'width': '100px',
            'disabled': false,
            'inputType': 'text',
            'prefixWidth': '40px'
          },
          'key': '1617169577000_62709'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_72387-0',
            'label': '文盲',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_72387-1',
            'label': '幼儿园',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_72387-2',
            'label': '小学',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_72387-3',
            'label': '初中',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_72387-4',
            'label': '高中',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_72387-5',
            'label': '大学',
            'marginRight': '10px'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '文化程度：',
            'prefixWidth': '80px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_72387'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefix': '其他：',
            'prefixWidth': '50px',
            'width': '100px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'input'
          },
          'key': '1617169577000_73371'
        }, {
          'score': 0,
          'type': 'text',
          'value': '',
          'config': {
            'label': '婚姻状况：',
            'width': '80px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'text'
          },
          'key': '1617169577000_78733'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefix': '已婚：',
            'prefixWidth': '50px',
            'width': '50px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'input',
            'suffix': '子'
          },
          'key': '1617169577000_97773'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefix': '',
            'prefixWidth': '',
            'width': '50px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'input',
            'suffix': '女'
          },
          'key': '1617169577000_47361'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_75124-0',
            'label': '平房'
          }, {
            'score': 0,
            'id': '1617169577000_75124-1',
            'label': '楼房',
            'children': [{
              'score': 0,
              'type': 'input',
              'value': '',
              'config': {
                'width': '100px',
                'prefix': '',
                'prefixWidth': '',
                'borderLine': true,
                'readonly': false,
                'disabled': true,
                'inputType': 'input',
                'suffix': '层',
                'keyDisabled': '1617169577000_75124-1'
              },
              'key': '1617169577000_224'
            }, {
              'score': 0,
              'type': 'text',
              'value': '',
              'config': {
                'label': '（',
                'width': '20px',
                'prefixWidth': '',
                'borderLine': true,
                'readonly': false,
                'disabled': false,
                'inputType': 'text',
                'suffix': ''
              },
              'key': '1617169577000_9579'
            }, {
              'options': [{
                'score': 0,
                'id': '1617169577000_93927-0',
                'label': '有电梯'
              }, {
                'score': 0,
                'id': '1617169577000_93927-1',
                'label': '无电梯'
              }],
              'score': 0,
              'type': 'checkbox',
              'value': [],
              'config': {
                'prefix': '',
                'prefixWidth': '',
                'borderLine': true,
                'readonly': false,
                'disabled': true,
                'inputType': 'checkbox',
                'isRadio': true,
                'keyDisabled': '1617169577000_75124-1'
              },
              'key': '1617169577000_93927'
            }, {
              'score': 0,
              'type': 'text',
              'value': '',
              'config': {
                'label': '）',
                'prefixWidth': '',
                'borderLine': true,
                'readonly': false,
                'disabled': false,
                'inputType': 'text',
                'suffix': ''
              },
              'key': '1617169577000_17206'
            }]
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '居住情况：',
            'prefixWidth': '80px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_75124'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_33502-0',
            'label': '与配偶同住',
            'marginLeft': '90px'
          }, {
            'score': 0,
            'id': '1617169577000_33502-1',
            'label': '与子女同住'
          }, {
            'score': 0,
            'id': '1617169577000_33502-2',
            'label': '与父母同住'
          }, {
            'score': 0,
            'id': '1617169577000_33502-3',
            'label': '单独居住',
            'marginRight': '71px'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '',
            'prefixWidth': '',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox'
          },
          'key': '1617169577000_33502'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_50058-0',
            'label': '兄弟'
          }, {
            'score': 0,
            'id': '1617169577000_50058-1',
            'label': '姐妹'
          }, {
            'score': 0,
            'id': '1617169577000_50058-2',
            'label': '家属'
          }, {
            'score': 0,
            'id': '1617169577000_50058-3',
            'label': '朋友'
          }, {
            'score': 0,
            'id': '1617169577000_50058-4',
            'label': '敬老院'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '社会支持：',
            'prefixWidth': '80px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox'
          },
          'key': '1617169577000_50058'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefix': '其他',
            'prefixWidth': '35px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'input',
            'width': '100px',
            'prefixAlign': 'right'
          },
          'key': '1617169577000_14337'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefix': '联系人',
            'prefixWidth': '50px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'width': '100px',
            'inputType': 'input'
          },
          'key': '1617169577000_64328'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefix': '电话：',
            'prefixWidth': '50px',
            'width': '90px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'input'
          },
          'key': '1617169577000_14813'
        }, {
          'options': [{
            'score': 0,
            'id': '1621217452000_89593-0',
            'label': '正常'
          }, {
            'score': 0,
            'id': '1621217452000_89593-1',
            'label': '较少'
          }, {
            'score': 0,
            'id': '1621217452000_89593-2',
            'label': '回避'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '社会交往：',
            'prefixWidth': '80px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox'
          },
          'key': '1621217452000_89593'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefix': '其他：',
            'prefixWidth': '80px',
            'prefixAlign': 'right',
            'width': '90px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'input'
          },
          'key': '1621218075000_5213'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_14364-0',
            'label': '无'
          }, {
            'score': 0,
            'id': '1617169577000_14364-1',
            'label': '有',
            'children': [{
              'score': 0,
              'type': 'text',
              'value': '',
              'config': {
                'label': '（',
                'width': '20px',
                'prefixWidth': '',
                'borderLine': true,
                'readonly': false,
                'disabled': false,
                'inputType': 'text'
              },
              'key': '1617169577000_7836'
            }, {
              'options': [{
                'score': 0,
                'id': '1617169577000_69623-0',
                'label': '佛教'
              }, {
                'score': 0,
                'id': '1617169577000_69623-1',
                'label': '道教'
              }, {
                'score': 0,
                'id': '1617169577000_69623-2',
                'label': '基督教'
              }, {
                'score': 0,
                'id': '1617169577000_69623-3',
                'label': '伊斯兰教'
              }, {
                'score': 0,
                'id': '1617169577000_69623-4',
                'label': '天主教'
              }],
              'score': 0,
              'type': 'checkbox',
              'value': [],
              'config': {
                'prefix': '',
                'prefixWidth': '',
                'borderLine': true,
                'readonly': false,
                'disabled': true,
                'inputType': 'checkbox',
                'keyDisabled': '1617169577000_14364-1'
              },
              'key': '1617169577000_69623'
            }, {
              'score': 0,
              'type': 'input',
              'value': '',
              'config': {
                'prefix': '其他',
                'width': '150px',
                'prefixWidth': '',
                'borderLine': true,
                'readonly': false,
                'disabled': true,
                'inputType': 'input',
                'keyDisabled': '1617169577000_14364-1'
              },
              'key': '1617169577000_44852'
            }, {
              'score': 0,
              'type': 'text',
              'value': '',
              'config': {
                'label': '）',
                'width': '20px',
                'prefixWidth': '',
                'borderLine': true,
                'readonly': false,
                'disabled': false,
                'inputType': 'text'
              },
              'key': '1617169577000_69526'
            }]
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '宗教信仰：',
            'prefixWidth': '80px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_14364'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_64841-0',
            'label': '自费'
          }, {
            'score': 0,
            'id': '1617169577000_64841-1',
            'label': '医保'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '费用来源：',
            'prefixWidth': '80px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_64841'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_88461-0',
            'label': '否'
          }, {
            'score': 0,
            'id': '1617169577000_88461-1',
            'label': '是',
            'children': [{
              'score': 0,
              'type': 'text',
              'value': '',
              'config': {
                'label': '（',
                'width': '20px',
                'prefixWidth': '',
                'borderLine': true,
                'readonly': false,
                'disabled': false,
                'inputType': 'text'
              },
              'key': '1617169577000_37959'
            }, {
              'options': [{
                'score': 0,
                'id': '1617169577000_40055-0',
                'label': '儿童',
                'marginRight': '15px'
              }, {
                'score': 0,
                'id': '1617169577000_40055-1',
                'label': '产/孕妇',
                'marginRight': '15px'
              }, {
                'score': 0,
                'id': '1617169577000_40055-2',
                'label': '终止妊娠',
                'marginRight': '15px'
              }, {
                'score': 0,
                'id': '1617169577000_40055-3',
                'label': '体弱老年',
                'marginRight': '15px'
              }, {
                'score': 0,
                'id': '1617169577000_40055-4',
                'label': '吸毒',
                'marginRight': '15px'
              }, {
                'score': 0,
                'id': '1617169577000_40055-5',
                'label': '酗酒',
                'marginRight': '15px'
              }, {
                'score': 0,
                'id': '1617169577000_40055-6',
                'label': '有自杀倾向',
                'marginRight': '15px'
              }, {
                'score': 0,
                'id': '1617169577000_40055-7',
                'label': '情绪失控或者精神障碍',
                'marginRight': '15px'
              }, {
                'score': 0,
                'id': '1617169577000_40055-8',
                'label': '放化疗患者',
                'marginRight': '15px'
              }, {
                'score': 0,
                'id': '1617169577000_40055-9',
                'label': '免疫抑制',
                'marginRight': '15px'
              }, {
                'score': 0,
                'id': '1617169577000_40055-10',
                'label': '传染病',
                'marginRight': '15px'
              }],
              'score': 0,
              'type': 'checkbox',
              'value': [],
              'config': {
                'prefix': '',
                'prefixWidth': '',
                'borderLine': true,
                'readonly': false,
                'disabled': true,
                'inputType': 'checkbox',
                'isRadio': true,
                'keyDisabled': '1617169577000_88461-1'
              },
              'key': '1617169577000_40055'
            }, {
              'score': 0,
              'type': 'text',
              'value': '',
              'config': {
                'label': ')',
                'width': '20px',
                'prefixWidth': '',
                'borderLine': true,
                'readonly': false,
                'disabled': false,
                'inputType': 'text'
              },
              'key': '1617169577000_98643'
            }]
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '特殊人群：',
            'prefixWidth': '80px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true,
            'noCenter': true,
            'noAlignCenter': true
          },
          'key': '1617169577000_88461'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '100%',
        'childWidth': '',
        'align': 'center',
        'gapTB': '2px',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '1px',
        'borderStyle': 'solid'
      },
      'key': '1617169577000_16522'
    }, {
      'columns': [{
        'padding': '0 0 0 5px',
        'gapLR': '0',
        'children': [{
          'score': 0,
          'mConfig': {},
          'type': 'text',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'label': '身体评估:',
            'align': 'left',
            'width': '999px',
            'disabled': false,
            'inputType': 'text'
          },
          'key': '1617169577000_35208'
        }, {
          'score': 0,
          'mConfig': {},
          'type': 'text',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'label': '生命体征:',
            'align': 'left',
            'width': '70px'
          },
          'key': '1617169577000_36239'
        }, {
          'score': 0,
          'mConfig': {},
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': 'T:',
            'prefixAlign': 'right',
            'width': '50px',
            'disabled': false,
            'inputType': 'text',
            'prefixWidth': '30px',
            'suffix': '℃',
            'suffixPaddingLeft': '10px'
          },
          'key': '1617169577000_99246'
        }, {
          'score': 0,
          'mConfig': {},
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': 'P:',
            'prefixAlign': 'right',
            'width': '50px',
            'disabled': false,
            'inputType': 'text',
            'prefixWidth': '50px',
            'suffix': '次/分',
            'suffixPaddingLeft': '10px'
          },
          'key': '1617169577000_81112'
        }, {
          'score': 0,
          'mConfig': {},
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': 'R:',
            'prefixAlign': 'right',
            'width': '50px',
            'disabled': false,
            'inputType': 'text',
            'prefixWidth': '50px',
            'suffix': '次/分',
            'suffixPaddingLeft': '10px'
          },
          'key': '1617169577000_31338'
        }, {
          'score': 0,
          'mConfig': {},
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': 'BP:',
            'prefixAlign': 'right',
            'width': '50px',
            'disabled': false,
            'inputType': 'text',
            'prefixWidth': '50px',
            'suffix': 'mmhg',
            'suffixPaddingLeft': '10px',
            'suffixWidth': '330px'
          },
          'key': '1617169577000_91632'
        }, {
          'score': 0,
          'mConfig': {},
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': '身高:',
            'prefixAlign': 'left',
            'width': '50px',
            'disabled': false,
            'inputType': 'text',
            'prefixWidth': '80px',
            'suffix': 'cm'
          },
          'key': '1617169577000_56438'
        }, {
          'score': 0,
          'mConfig': {},
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': '体重:',
            'prefixAlign': 'right',
            'width': '50px',
            'disabled': false,
            'inputType': 'text',
            'prefixWidth': '40px',
            'suffix': 'kg'
          },
          'key': '1617169577000_52490'
        }, {
          'score': 0,
          'mConfig': {},
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': '体重指数:',
            'prefixAlign': 'right',
            'width': '100px',
            'disabled': false,
            'inputType': 'text',
            'prefixWidth': '110px'
          },
          'key': '1617169577000_21826'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_89845-0',
            'label': '清楚'
          }, {
            'score': 0,
            'id': '1617169577000_89845-1',
            'label': '倦怠'
          }, {
            'score': 0,
            'id': '1617169577000_89845-2',
            'label': '烦躁'
          }, {
            'score': 0,
            'id': '1617169577000_89845-3',
            'label': '嗜睡'
          }, {
            'score': 0,
            'id': '1617169577000_89845-4',
            'label': '谵妄'
          }, {
            'score': 0,
            'id': '1617169577000_89845-5',
            'label': '昏迷'
          }, {
            'score': 0,
            'id': '1617169577000_89845-6',
            'label': '其他'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '神志：',
            'prefixWidth': '80px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_89845'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_526-0',
            'label': '正常',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_526-1',
            'label': '弱视',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_526-2',
            'label': '近视',
            'marginRight': '10px',
            'children': [{
              'score': 0,
              'type': 'text',
              'value': '',
              'config': {
                'label': '（',
                'width': '20px',
                'prefixWidth': '',
                'borderLine': true,
                'readonly': false,
                'disabled': false,
                'inputType': 'text',
                'suffix': ''
              },
              'key': '1617169577000_56585'
            }, {
              'options': [{
                'score': 0,
                'id': '1617169577000_95293-0',
                'label': '眼镜',
                'marginRight': '10px'
              }, {
                'score': 0,
                'id': '1617169577000_95293-1',
                'label': '眼罩',
                'marginRight': '10px'
              }, {
                'score': 0,
                'id': '1617169577000_95293-2',
                'label': '隐形眼镜',
                'marginRight': '10px'
              }, {
                'score': 0,
                'id': '1617169577000_95293-3',
                'label': '远视',
                'marginRight': '10px'
              }],
              'score': 0,
              'type': 'checkbox',
              'value': [],
              'config': {
                'prefix': '',
                'prefixWidth': '',
                'borderLine': true,
                'readonly': false,
                'disabled': false,
                'inputType': 'checkbox',
                'isRadio': true,
                'keyDisabled': '1617169577000_526-2'
              },
              'key': '1617169577000_95293'
            }, {
              'score': 0,
              'type': 'text',
              'value': '',
              'config': {
                'label': '）',
                'prefixWidth': '',
                'borderLine': true,
                'readonly': false,
                'disabled': false,
                'inputType': 'text',
                'suffix': ''
              },
              'key': '1617169577000_7417'
            }]
          }, {
            'score': 0,
            'id': '1617169577000_526-3',
            'label': '失明',
            'marginRight': '10px'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '视力：',
            'prefixWidth': '80px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_526'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefix': '其他：',
            'prefixWidth': '60px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'input',
            'isRadio': true,
            'width': '200px'
          },
          'key': '1617169577000_57782'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_29108-0',
            'label': '正常',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_29108-1',
            'label': '弱听',
            'marginRight': '10px',
            'children': [{
              'score': 0,
              'type': 'text',
              'value': '',
              'config': {
                'label': '（',
                'width': '20px',
                'prefixWidth': '',
                'borderLine': true,
                'readonly': false,
                'disabled': false,
                'inputType': 'text',
                'suffix': ''
              },
              'key': '1617169577000_62890'
            }, {
              'options': [{
                'score': 0,
                'id': '1617169577000_54777-0',
                'label': '左',
                'marginRight': '10px'
              }, {
                'score': 0,
                'id': '1617169577000_54777-1',
                'label': '右',
                'marginRight': '10px'
              }],
              'score': 0,
              'type': 'checkbox',
              'value': [],
              'config': {
                'prefix': '',
                'prefixWidth': '',
                'borderLine': true,
                'readonly': false,
                'disabled': true,
                'inputType': 'checkbox',
                'keyDisabled': '1617169577000_29108-1'
              },
              'key': '1617169577000_54777'
            }, {
              'score': 0,
              'type': 'text',
              'value': '',
              'config': {
                'label': '）',
                'prefixWidth': '',
                'borderLine': true,
                'readonly': false,
                'disabled': false,
                'inputType': 'text',
                'suffix': ''
              },
              'key': '1617169577000_19246'
            }]
          }, {
            'score': 0,
            'id': '1617169577000_29108-2',
            'label': '失聪',
            'marginRight': '10px',
            'children': [{
              'score': 0,
              'type': 'text',
              'value': '',
              'config': {
                'label': '（',
                'width': '20px',
                'prefixWidth': '',
                'borderLine': true,
                'readonly': false,
                'disabled': false,
                'inputType': 'text',
                'suffix': ''
              },
              'key': '1617169577000_99548'
            }, {
              'options': [{
                'score': 0,
                'id': '1617169577000_31792-0',
                'label': '左',
                'marginRight': '10px'
              }, {
                'score': 0,
                'id': '1617169577000_31792-1',
                'label': '右',
                'marginRight': '10px'
              }],
              'score': 0,
              'type': 'checkbox',
              'value': [],
              'config': {
                'prefix': '',
                'prefixWidth': '',
                'borderLine': true,
                'readonly': false,
                'disabled': true,
                'inputType': 'checkbox',
                'keyDisabled': '1617169577000_29108-2'
              },
              'key': '1617169577000_31792'
            }, {
              'score': 0,
              'type': 'text',
              'value': '',
              'config': {
                'label': '）',
                'prefixWidth': '',
                'borderLine': true,
                'readonly': false,
                'disabled': false,
                'inputType': 'text',
                'suffix': ''
              },
              'key': '1617169577000_17763'
            }]
          }, {
            'score': 0,
            'id': '1617169577000_29108-3',
            'label': '耳鸣',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_29108-4',
            'label': '助听',
            'marginRight': '10px'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '听力：',
            'prefixWidth': '80px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'isRadio': true,
            'inputType': 'checkbox'
          },
          'key': '1617169577000_29108'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_41603-0',
            'label': '正常',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_41603-1',
            'label': '黄染',
            'marginRight': '5px'
          }, {
            'score': 0,
            'id': '1617169577000_41603-2',
            'label': '苍白',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_41603-3',
            'label': '红斑',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_41603-4',
            'label': '紫绀',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_41603-5',
            'label': '压疮',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_41603-6',
            'label': '潮红',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_41603-7',
            'label': '溃烂',
            'marginRight': '10px'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '皮肤：',
            'prefixWidth': '80px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox'
          },
          'key': '1617169577000_41603'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefix': '其他',
            'prefixWidth': '35px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'input',
            'width': '200px'
          },
          'key': '1617169577000_40962'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_17105-0',
            'label': '正常',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_17105-1',
            'label': '便秘',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_17105-5',
            'label': '腹泻',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_17105-2',
            'label': '便血',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_17105-3',
            'label': '失禁',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_17105-4',
            'label': '造瘘',
            'marginRight': '10px'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '排便：',
            'prefixWidth': '80px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_17105'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefix': '类型',
            'prefixWidth': '35px',
            'borderLine': true,
            'width': '146px',
            'readonly': false,
            'disabled': false,
            'inputType': 'input',
            'isRadio': true
          },
          'key': '1617169577000_48512'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_25789-0',
            'label': '能自理'
          }, {
            'score': 0,
            'id': '1617169577000_25789-1',
            'label': '不能自理'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '',
            'prefixWidth': '',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_25789'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_27217-0',
            'label': '正常',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_27217-1',
            'label': '尿频',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_27217-2',
            'label': '尿急',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_27217-3',
            'label': '尿痛',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_27217-4',
            'label': '尿潴留',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_27217-5',
            'label': '无尿',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_27217-6',
            'label': '血尿',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_27217-7',
            'label': '少尿',
            'marginRight': '10px'
          }, {
            'score': 0,
            'id': '1617169577000_27217-8',
            'label': '多尿',
            'marginRight': '10px'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '排尿：',
            'prefixWidth': '80px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true,
            'noCenter': true
          },
          'key': '1617169577000_27217'
        }, {
          'score': 0,
          'type': 'input',
          'value': '',
          'config': {
            'prefix': '其他',
            'prefixWidth': '35px',
            'borderLine': true,
            'width': '200px',
            'readonly': false,
            'disabled': false,
            'inputType': 'input',
            'isRadio': true,
            'noCenter': true
          },
          'key': '1617169577000_58093'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_77061-0',
            'label': '自如'
          }, {
            'score': 0,
            'id': '1617169577000_77061-1',
            'label': '障碍'
          }, {
            'score': 0,
            'id': '1617169577000_77061-2',
            'label': '肢体瘫痪',
            'children': [{
              'score': 0,
              'type': 'text',
              'value': '',
              'config': {
                'label': '（',
                'width': '20px',
                'inputType': 'text'
              },
              'key': '1617169577000_56103'
            }, {
              'options': [{
                'score': 0,
                'id': '1617169577000_21009-0',
                'label': '左上'
              }, {
                'score': 0,
                'id': '1617169577000_21009-1',
                'label': '左下'
              }, {
                'score': 0,
                'id': '1617169577000_21009-2',
                'label': '右上'
              }, {
                'score': 0,
                'id': '1617169577000_21009-3',
                'label': '右下'
              }],
              'score': 0,
              'type': 'checkbox',
              'value': [],
              'config': {
                'prefix': '',
                'prefixWidth': '',
                'borderLine': true,
                'readonly': false,
                'disabled': true,
                'inputType': 'checkbox',
                'noCenter': true,
                'keyDisabled': '1617169577000_77061-2'
              },
              'key': '1617169577000_21009'
            }, {
              'score': 0,
              'type': 'text',
              'value': '',
              'config': {
                'label': ')',
                'width': '20px',
                'inputType': 'text'
              },
              'key': '1617169577000_3691'
            }]
          }, {
            'score': 0,
            'id': '1617169577000_77061-3',
            'label': '其他'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '活动状态：',
            'prefixWidth': '80px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true,
            'noCenter': true
          },
          'key': '1617169577000_77061'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_32545-0',
            'label': '正常'
          }, {
            'score': 0,
            'id': '1617169577000_32545-1',
            'label': '易醒'
          }, {
            'score': 0,
            'id': '1617169577000_32545-2',
            'label': '失眠'
          }, {
            'score': 0,
            'id': '1617169577000_32545-3',
            'label': '多眠'
          }, {
            'score': 0,
            'id': '1617169577000_32545-4',
            'label': '其他',
            'marginRight': '367px'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '睡眠：',
            'prefixWidth': '80px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true,
            'noCenter': true
          },
          'key': '1617169577000_32545'
        },
        {
          'columns': [{
            'padding': '',
            'gapLR': '0',
            'children': [{
              'type': 'text',
              'value': '',
              'config': {
                'width': '180px',
                'weight': '',
                'label': '自理能力（ADL评分）：',
                'align': 'left'
              },
              'key': '1619155311000_39306'
            }, {
              'type': 'button',
              'value': '',
              'config': {
                'changeText': false,
                'scoreKey': '1617169577000_65186',
                'size': 'mini',
                'labelAfter': '查看评估内容',
                'label': '点击开始评估',
                'btnType': 'admissionImport',
                'moduleId': '10037',
                'importTitle': '自理能力（ADL评分）：',
                'printHidden': true,
                'importTime': 'last'
              },
              'key': '1619155311000_88669'
            }, {
              'score': 0,
              'type': 'input',
              'value': '',
              'config': {
                'prefix': '',
                'prefixWidth': '50px',
                'width': '50px',
                'borderLine': true,
                'readonly': false,
                'disabled': false,
                'inputType': 'input',
                'noCenter': true,
                'suffix': '分'
              },
              'key': '1617169577000_65186'
            }],
            'flex': 1,
            'justify': 'flex-start',
            'width': '',
            'childWidth': 'auto',
            'align': 'center',
            'gapTB': '0',
            'direction': 'row'
          }],
          'type': 'grid',
          'value': '',
          'config': {
            'borderColor': '#ddd',
            'borderWidth': '0',
            'borderStyle': 'solid'
          },
          'key': '1619155311000_32318'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '100%',
        'childWidth': '',
        'align': 'center',
        'gapTB': '2px',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '1px',
        'borderStyle': 'solid'
      },
      'key': '1617169577000_26705'
    }, {
      'columns': [{
        'padding': '0 0 0 5px',
        'gapLR': '0',
        'children': [{
          'options': [{
            'score': 0,
            'id': '1617169577000_19738-0',
            'label': '无'
          }, {
            'score': 0,
            'id': '1617169577000_19738-1',
            'label': '有',
            'marginRight': '300px'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '导管评估：',
            'prefixWidth': '80px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_19738'
        },
        {
          'columns': [{
            'padding': '',
            'gapLR': '0',
            'children': [{
              'type': 'text',
              'value': '',
              'config': {
                'weight': '',
                'label': '非计划拔管风险评估分值：',
                'align': 'left'
              },
              'key': '1619155311000_96300'
            }, {
              'type': 'button',
              'value': '',
              'config': {
                'changeText': false,
                'scoreKey': '1617169577000_77811',
                'size': 'mini',
                'labelAfter': '查看评估内容',
                'label': '点击开始评估',
                'btnType': 'admissionImport',
                'moduleId': '10029',
                'importTitle': '非计划拔管风险评估：',
                'printHidden': true,
                'importTime': 'last'
              },
              'key': '1619155311000_1368'
            }, {
              'score': 0,
              'type': 'input',
              'value': '',
              'config': {
                'borderLine': true,
                'readonly': false,
                'width': '50px',
                'disabled': false,
                'noCenter': true,
                'inputType': 'input',
                'prefixWidth': '50px',
                'suffix': '分'
              },
              'key': '1617169577000_77811'
            }],
            'flex': 1,
            'justify': 'flex-start',
            'width': '',
            'childWidth': 'auto',
            'align': 'center',
            'gapTB': '0',
            'direction': 'row'
          }],
          'type': 'grid',
          'value': '',
          'config': {
            'borderColor': '#ddd',
            'borderWidth': '0',
            'borderStyle': 'solid'
          },
          'key': '1619155311000_74413'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '100%',
        'childWidth': '100%',
        'align': 'center',
        'gapTB': '2px',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '1px',
        'borderStyle': 'solid'
      },
      'key': '1617169577000_6661'
    }, {
      'columns': [{
        'padding': '0 0 0 5px',
        'gapLR': '0',
        'children': [{
          'score': 0,
          'mConfig': {},
          'type': 'text',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'label': '营养筛查:',
            'align': 'left',
            'width': '980px',
            'weight': '600',
            'disabled': false,
            'inputType': 'text'
          },
          'key': '1617169577000_18245'
        }, {
          'score': 0,
          'mConfig': {},
          'type': 'text',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'label': '是否属于下列情况:',
            'align': 'left',
            'width': '980px'
          },
          'key': '1617169577000_58239'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_26157-0',
            'label': '否'
          }, {
            'score': 0,
            'id': '1617169577000_26157-1',
            'label': '是',
            'marginRight': '200px'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': 'BMI<18.5',
            'prefixWidth': '380px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_26157'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_72355-0',
            'label': '否'
          }, {
            'score': 0,
            'id': '1617169577000_72355-1',
            'label': '是',
            'marginRight': '200px'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '三个月内体重减轻了吗？（体重减轻5%）',
            'prefixWidth': '380px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_72355'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_16570-0',
            'label': '否'
          }, {
            'score': 0,
            'id': '1617169577000_16570-1',
            'label': '是',
            'marginRight': '200px'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '上周内吃饭减少了吗？（饭量减少25%）',
            'prefixWidth': '380px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_16570'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_19166-0',
            'label': '否'
          }, {
            'score': 0,
            'id': '1617169577000_19166-1',
            'label': '是',
            'marginRight': '200px'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '患者有严重的疾病，（如入住ICU接受治疗）?',
            'prefixWidth': '380px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_19166'
        },
        {
          'columns': [{
            'padding': '',
            'gapLR': '0',
            'children': [{
              'type': 'text',
              'value': '',
              'config': {
                'weight': '',
                'label': '有以上情况之一，说明有营养问题的可能，进一步营养风险筛查评估分值：',
                'align': 'left'
              },
              'key': '1619155311000_21385'
            }, {
              'type': 'button',
              'value': '',
              'config': {
                'changeText': false,
                'scoreKey': '1617169577000_56635',
                'size': 'mini',
                'labelAfter': '查看评估内容',
                'label': '点击开始评估',
                'btnType': 'admissionImport',
                'moduleId': '10042',
                'importTitle': '营养风险评估：',
                'printHidden': true,
                'importTime': 'last'
              },
              'key': '1619155311000_99308'
            }, {
              'score': 0,
              'type': 'input',
              'value': '',
              'config': {
                'borderLine': true,
                'readonly': false,
                'prefixWidth': '50px',
                'width': '50px',
                'disabled': false,
                'noCenter': true,
                'inputType': 'input',
                'suffix': '分(>=3分有营养风险通知医生，>=5分请营养科会诊)'
              },
              'key': '1617169577000_56635'
            }],
            'flex': 1,
            'justify': 'flex-start',
            'width': '',
            'childWidth': 'auto',
            'align': 'center',
            'gapTB': '0',
            'direction': 'row'
          }],
          'type': 'grid',
          'value': '',
          'config': {
            'borderColor': '#ddd',
            'borderWidth': '0',
            'borderStyle': 'solid'
          },
          'key': '1619155311000_71868'
        },
        {
          'options': [{
            'score': 0,
            'id': '1617169577000_45817-0',
            'label': '无以上情况',
            'marginRight': '900px'
          }, {
            'score': 0,
            'id': '1617169577000_45817-1',
            'label': '不合适'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '',
            'prefixWidth': '',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_45817'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '100%',
        'childWidth': '100%',
        'align': 'center',
        'gapTB': '2px',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '1px',
        'borderStyle': 'solid'
      },
      'key': '1617169577000_52761'
    }, {
      'columns': [{
        'padding': '0 0 0 5px',
        'gapLR': '0',
        'children': [{
          'score': 0,
          'mConfig': {},
          'type': 'text',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'label': '疼痛筛查:',
            'align': 'left',
            'width': '980px',
            'weight': '600',
            'disabled': false,
            'inputType': 'text'
          },
          'key': '1617169577000_58885'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_18378-0',
            'label': '否'
          }, {
            'score': 0,
            'id': '1617169577000_18378-1',
            'label': '是'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '您现在有疼痛吗？',
            'prefixWidth': '380px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_18378'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_70107-0',
            'label': '否'
          }, {
            'score': 0,
            'id': '1617169577000_70107-1',
            'label': '是'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '晚上有无因疼痛而影响睡眠：',
            'prefixWidth': '380px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_70107'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_30988-0',
            'label': '否'
          }, {
            'score': 0,
            'id': '1617169577000_30988-1',
            'label': '是'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '有无因疼痛而影响活动',
            'prefixWidth': '380px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_30988'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_57757-0',
            'label': '否'
          }, {
            'score': 0,
            'id': '1617169577000_57757-1',
            'label': '是'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '是否每天都有疼痛：',
            'prefixWidth': '380px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_57757'
        }, {
          'columns': [{
            'padding': '',
            'gapLR': '0',
            'children': [{
              'type': 'text',
              'value': '',
              'config': {
                'weight': '',
                'label': '如果有疼痛，护士根据《疼痛评估单》进行疼痛评估，评估分值：',
                'align': 'left'
              },
              'key': '1619155311000_41934'
            }, {
              'type': 'button',
              'value': '',
              'config': {
                'changeText': false,
                'scoreKey': '1617169577000_47217',
                'size': 'mini',
                'labelAfter': '查看评估内容',
                'label': '点击开始评估',
                'btnType': 'admissionImport',
                'moduleId': '10031',
                'importTitle': '疼痛评估：',
                'printHidden': true,
                'importTime': 'last'
              },
              'key': '1619155311000_72080'
            }, {
              'score': 0,
              'type': 'input',
              'value': '',
              'config': {
                'borderLine': true,
                'readonly': false,
                'width': '50px',
                'prefixWidth': '50px',
                'disabled': false,
                'noCenter': true,
                'inputType': 'input',
                'suffix': '分'
              },
              'key': '1617169577000_47217'
            }],
            'flex': 1,
            'justify': 'flex-start',
            'width': '',
            'childWidth': 'auto',
            'align': 'center',
            'gapTB': '0',
            'direction': 'row'
          }],
          'type': 'grid',
          'value': '',
          'config': {
            'borderColor': '#ddd',
            'borderWidth': '0',
            'borderStyle': 'solid'
          },
          'key': '1619155311000_28311'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_8982-0',
            'label': '无以上情况',
            'marginRight': '900px'
          }, {
            'score': 0,
            'id': '1617169577000_8982-1',
            'label': '不合适'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '',
            'prefixWidth': '',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_8982'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '100%',
        'childWidth': '100%',
        'align': 'center',
        'gapTB': '2px',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '1px',
        'borderStyle': 'solid'
      },
      'key': '1617169577000_93471'
    }, {
      'columns': [{
        'padding': '0 0 0 5px',
        'gapLR': '0',
        'children': [{
          'score': 0,
          'mConfig': {},
          'type': 'text',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'label': '心理评估:',
            'align': 'left',
            'width': '980px',
            'weight': '600',
            'disabled': false,
            'inputType': 'text'
          },
          'key': '1617169577000_52332'
        }, {
          'score': 0,
          'mConfig': {},
          'type': 'text',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'label': '是否属于下列情况：',
            'align': 'left',
            'width': '980px'
          },
          'key': '1617169577000_26543'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_27297-0',
            'label': '紧张'
          }, {
            'score': 0,
            'id': '1617169577000_27297-1',
            'label': '抑郁'
          }, {
            'score': 0,
            'id': '1617169577000_27297-2',
            'label': '焦虑'
          }, {
            'score': 0,
            'id': '1617169577000_27297-3',
            'label': '恐惧'
          }, {
            'score': 0,
            'id': '1617169577000_27297-4',
            'label': '恶性肿瘤'
          }, {
            'score': 0,
            'id': '1617169577000_27297-5',
            'label': '大手术前焦虑、恐惧'
          }, {
            'score': 0,
            'id': '1617169577000_27297-6',
            'label': '产后抑郁'
          }, {
            'score': 0,
            'id': '1617169577000_27297-7',
            'label': '临终前恐惧'
          }, {
            'score': 0,
            'id': '1617169577000_27297-8',
            'label': '慢性疼痛焦虑'
          }, {
            'score': 0,
            'id': '1617169577000_27297-9',
            'label': '有重大精神创伤'
          }, {
            'score': 0,
            'id': '1617169577000_27297-10',
            'label': '有心理评估要求'
          }, {
            'score': 0,
            'id': '1617169577000_27297-11',
            'label': '有自杀倾向'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '',
            'prefixWidth': '',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox'
          },
          'key': '1617169577000_27297'
        }, {
          'score': 0,
          'mConfig': {},
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': '其他：',
            'prefixWidth': '60px',
            'width': '440px',
            'inputType': 'input',
            'noCenter': true
          },
          'key': '1617169577000_25119'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_19302-0',
            'label': '是（通知医生）'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '有以上情况之一，说明有心理问题的可能，专业心理医师评估需求：',
            'prefixWidth': '440px',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_19302'
        }, {
          'options': [{
            'score': 0,
            'id': '1617169577000_82431-0',
            'label': '无以上情况',
            'marginRight': '900px'
          }, {
            'score': 0,
            'id': '1617169577000_82431-1',
            'label': '不合适'
          }],
          'score': 0,
          'type': 'checkbox',
          'value': [],
          'config': {
            'prefix': '',
            'prefixWidth': '',
            'borderLine': true,
            'readonly': false,
            'disabled': false,
            'inputType': 'checkbox',
            'isRadio': true
          },
          'key': '1617169577000_82431'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '100%',
        'childWidth': '100%',
        'align': 'center',
        'gapTB': '2px',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '1px',
        'borderStyle': 'solid'
      },
      'key': '1617169577000_78394'
    }, {
      'columns': [{
        'padding': '0 0 0 5px',
        'gapLR': '0',
        'children': [{
          'columns': [{
            'padding': '',
            'gapLR': '0',
            'children': [{
              'type': 'text',
              'value': '',
              'config': {
                'weight': '',
                'label': '跌倒风险评估分值：',
                'align': 'left'
              },
              'key': '1619155311000_30177'
            }, {
              'type': 'button',
              'value': '',
              'config': {
                'changeText': false,
                'scoreKey': '1617169577000_81003',
                'size': 'mini',
                'labelAfter': '查看评估内容',
                'label': '点击开始评估',
                'btnType': 'admissionImport',
                'moduleId': '10030',
                'importTitle': '跌倒风险评估:',
                'printHidden': true,
                'importTime': 'last'
              },
              'key': '1619155311000_27424'
            }, {
              'score': 0,
              'type': 'input',
              'value': '',
              'config': {
                'borderLine': true,
                'readonly': false,
                'width': '50px',
                'prefixWidth': '50px',
                'disabled': false,
                'noCenter': true,
                'inputType': 'input',
                'suffix': '分'
              },
              'key': '1617169577000_81003'
            }],
            'flex': 1,
            'justify': 'flex-start',
            'width': '',
            'childWidth': 'auto',
            'align': 'center',
            'gapTB': '0',
            'direction': 'row'
          }],
          'type': 'grid',
          'value': '',
          'config': {
            'borderColor': '#ddd',
            'borderWidth': '0',
            'borderStyle': 'solid'
          },
          'key': '1619155311000_13353'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '',
        'childWidth': '',
        'align': 'center',
        'gapTB': '2px',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '1px',
        'borderStyle': 'solid'
      },
      'key': '1617169577000_92850'
    }, {
      'columns': [{
        'padding': '0 0 0 5px',
        'gapLR': '0',
        'children': [{
          'columns': [{
            'padding': '',
            'gapLR': '0',
            'children': [{
              'type': 'text',
              'value': '',
              'config': {
                'weight': '',
                'label': '压疮风险评估分值：',
                'align': 'left'
              },
              'key': '1619155311000_98695'
            }, {
              'type': 'button',
              'value': '',
              'config': {
                'changeText': false,
                'scoreKey': '1617169577000_99092',
                'size': 'mini',
                'labelAfter': '查看评估内容',
                'label': '点击开始评估',
                'btnType': 'admissionImport',
                'moduleId': '10028',
                'importTitle': '压疮风险评估:',
                'printHidden': true,
                'importTime': 'last'
              },
              'key': '1619155311000_63303'
            }, {
              'score': 0,
              'type': 'input',
              'value': '',
              'config': {
                'borderLine': true,
                'readonly': false,
                'width': '50px',
                'prefixWidth': '50px',
                'disabled': false,
                'noCenter': true,
                'inputType': 'input',
                'suffix': '分'
              },
              'key': '1617169577000_99092'
            }],
            'flex': 1,
            'justify': 'flex-start',
            'width': '',
            'childWidth': 'auto',
            'align': 'center',
            'gapTB': '0',
            'direction': 'row'
          }],
          'type': 'grid',
          'value': '',
          'config': {
            'borderColor': '#ddd',
            'borderWidth': '0',
            'borderStyle': 'solid'
          },
          'key': '1619155311000_66872'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '',
        'childWidth': '',
        'align': 'center',
        'gapTB': '2px',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '1px',
        'borderStyle': 'solid'
      },
      'key': '1617169577000_2211'
    }, {
      'columns': [{
        'padding': '0 0 0 5px',
        'gapLR': '0',
        'children': [{
          'columns': [{
            'padding': '',
            'gapLR': '0',
            'children': [{
              'type': 'text',
              'value': '',
              'config': {
                'weight': '',
                'label': '深静脉血栓风险评估分值：',
                'align': 'left'
              },
              'key': '1619155311000_67702'
            }, {
              'type': 'button',
              'value': '',
              'config': {
                'changeText': false,
                'scoreKey': '1617169577000_34196',
                'size': 'mini',
                'labelAfter': '查看评估内容',
                'label': '点击开始评估',
                'btnType': 'admissionImport',
                'moduleId': '10034',
                'importTitle': '深静脉血栓风险评估:',
                'printHidden': true,
                'importTime': 'last'
              },
              'key': '1619155311000_64487'
            }, {
              'score': 0,
              'type': 'input',
              'value': '',
              'config': {
                'borderLine': true,
                'readonly': false,
                'width': '50px',
                'prefixWidth': '50px',
                'disabled': false,
                'noCenter': true,
                'inputType': 'input',
                'suffix': '分'
              },
              'key': '1617169577000_34196'
            }],
            'flex': 1,
            'justify': 'flex-start',
            'width': '',
            'childWidth': 'auto',
            'align': 'center',
            'gapTB': '0',
            'direction': 'row'
          }],
          'type': 'grid',
          'value': '',
          'config': {
            'borderColor': '#ddd',
            'borderWidth': '0',
            'borderStyle': 'solid'
          },
          'key': '1619155311000_90808'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '',
        'childWidth': '',
        'align': 'center',
        'gapTB': '2px',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '1px',
        'borderStyle': 'solid'
      },
      'key': '1617169577000_13786'
    }, {
      'columns': [{
        'padding': '0 0 0 5px',
        'gapLR': '0',
        'children': [{
          'score': 0,
          'mConfig': {},
          'type': 'input',
          'value': '',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': '责任护士:',
            'prefixAlign': 'left',
            'width': '92px',
            'disabled': false,
            'inputType': 'text',
            'prefixWidth': '70px'
          },
          'key': '1617169577000_84803'
        }, {
          'score': 0,
          'mConfig': {},
          'type': 'date',
          'value': '',
          'default': 'now',
          'config': {
            'borderLine': true,
            'readonly': false,
            'prefix': '日期时间:',
            'prefixAlign': 'left',
            'width': '170px',
            'disabled': false,
            'type': 'date',
            'prefixWidth': '90px',
            'noCenter': true
          },
          'key': '1617169577000_175512'
        }],
        'flex': 1,
        'justify': 'flex-start',
        'width': '100%',
        'childWidth': '',
        'align': 'center',
        'gapTB': '2px',
        'direction': 'row'
      }],
      'type': 'grid',
      'value': '',
      'config': {
        'borderColor': '#ddd',
        'borderWidth': '0',
        'borderStyle': 'solid'
      },
      'key': '1617169577000_16571'
    }]
