const wnms = "/wnms";
const hpms = "/hpms";
const passport = "/passport";
const ifms = "/ifms";
const smms = "/smms";
const qsms = "/qsms";
const bnms = "/bnms";
const fuds = "/fuds";
const pcms = "/pcms";
const bmms = "/bmms";
const tdms = "/tdms";
export { wnms, hpms, passport, ifms, smms, qsms, bnms, fuds, pcms, bmms, tdms };
